// Created by Crowbar 0.74

$modelname "hybridPhysx/airliner_right_wing_secondary_2.mdl"

$bodygroup "studio"
{
	studio "airliner_right_wing_secondary_2.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0 "baked_RW_debris_secondary_117"

$cdmaterials "models\hybridPhysx\"


$cbox 0 0 0 0 0 0

$bbox -1817.847 1446.289 1115.377 -1298.459 2202.988 1245.206

$definebone "airliner_right_wing_secondary_2" "" 4384.638672 988.29126 3817.847168 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_101" "airliner_right_wing_secondary_2" 130.902344 22.680176 28.299316 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_102" "airliner_right_wing_secondary_2" 317.552734 -9.975159 -154.331299 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_103" "airliner_right_wing_secondary_2" 144.566406 1.701904 -10.680664 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_104" "airliner_right_wing_secondary_2" 217.789063 3.44751 196.730957 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_105" "airliner_right_wing_secondary_2" 230.037109 18.405884 87.584961 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_106" "airliner_right_wing_secondary_2" 201.052246 12.599365 -2.849609 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_107" "airliner_right_wing_secondary_2" 313.415039 27.52832 57.52124 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_108" "airliner_right_wing_secondary_2" 286.488281 4.241943 -23.683594 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_109" "airliner_right_wing_secondary_2" 325.644531 -23.85083 -179.140381 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_110" "airliner_right_wing_secondary_2" 245.369141 16.989197 150.303223 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_111" "airliner_right_wing_secondary_2" 342.798828 -45.760132 -106.15625 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_112" "airliner_right_wing_secondary_2" 324.256836 -43.32666 237.856445 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_113" "airliner_right_wing_secondary_2" 222.49707 -5.575317 3.263672 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_114" "airliner_right_wing_secondary_2" 251.979492 17.300049 90.116943 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_115" "airliner_right_wing_secondary_2" 93.723633 24.511108 -14.642578 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_116" "airliner_right_wing_secondary_2" 375.308594 -63.150513 81.890137 0 -0.000057 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_117" "airliner_right_wing_secondary_2" -283.02002 50.07373 -242.500732 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_118" "airliner_right_wing_secondary_2" -203.334961 42.53772 -207.537109 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_119" "airliner_right_wing_secondary_2" -358.127441 58.238281 -199.174805 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_120" "airliner_right_wing_secondary_2" -328.888672 59.729614 -236.726074 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_121" "airliner_right_wing_secondary_2" -365.156982 60.317993 -212.17041 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_122" "airliner_right_wing_secondary_2" -177.15332 33.071045 -79.187988 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_123" "airliner_right_wing_secondary_2" -200.577637 34.889221 -127.307373 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_124" "airliner_right_wing_secondary_2" -156.423828 31.183105 -114.600586 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_125" "airliner_right_wing_secondary_2" -199.839844 36.185059 -141.986816 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_126" "airliner_right_wing_secondary_2" -178.367676 44.349121 -85.693115 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_127" "airliner_right_wing_secondary_2" -188.051758 49.443115 -130.559082 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_128" "airliner_right_wing_secondary_2" -178.793945 46.837524 -156.637207 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_129" "airliner_right_wing_secondary_2" -156.166992 36.196289 -62.65332 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_130" "airliner_right_wing_secondary_2" -361.253662 53.575562 -202.243652 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_131" "airliner_right_wing_secondary_2" -142.024902 29.065369 -52.687988 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_132" "airliner_right_wing_secondary_2" -150.219727 44.154541 -71.603516 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_133" "airliner_right_wing_secondary_2" -176.280273 34.643982 -151.274414 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_134" "airliner_right_wing_secondary_2" -335.523438 51.076416 -222.018066 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_135" "airliner_right_wing_secondary_2" -339.217041 62.399902 -218.254639 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_136" "airliner_right_wing_secondary_2" -157.498535 46.977051 -108.682373 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_137" "airliner_right_wing_secondary_2" -170.455566 31.592407 -84.574707 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_138" "airliner_right_wing_secondary_2" -192.370117 45.864258 -186.300781 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_139" "airliner_right_wing_secondary_2" -302.359863 56.474731 -241.928955 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_140" "airliner_right_wing_secondary_2" -206.185547 38.58313 -168.789795 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_141" "airliner_right_wing_secondary_2" -177.169922 48.073975 -144.84668 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_142" "airliner_right_wing_secondary_2" -152.669922 28.362183 -77.02002 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_143" "airliner_right_wing_secondary_2" -303.01416 58.033447 -217.905518 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_144" "airliner_right_wing_secondary_2" -170.207031 48.390869 -112.064209 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_145" "airliner_right_wing_secondary_2" -298.359375 49.116943 -233.963867 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_146" "airliner_right_wing_secondary_2" -352.396484 62.911133 -207.257324 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_147" "airliner_right_wing_secondary_2" -183.581055 34.17688 -128.418457 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_148" "airliner_right_wing_secondary_2" -175.911133 38.922241 -71.989258 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_149" "airliner_right_wing_secondary_2" -194.805176 48.080322 -170.265625 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_150" "airliner_right_wing_secondary_2" -162.822266 46.55481 -142.914063 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_151" "airliner_right_wing_secondary_2" -143.371094 46.134521 -93.140869 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_152" "airliner_right_wing_secondary_2" -197.518066 37.771484 -177.891113 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_153" "airliner_right_wing_secondary_2" -140.133789 35.922485 -52.044922 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_154" "airliner_right_wing_secondary_2" -302.705078 57.101929 -228.630859 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_155" "airliner_right_wing_secondary_2" -160.688477 30.336304 -104.254639 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_156" "airliner_right_wing_secondary_2" -170.820313 47.123535 -93.633789 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_157" "airliner_right_wing_secondary_2" -356.782959 51.755615 -209.459473 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_158" "airliner_right_wing_secondary_2" -310.655762 49.210693 -218.067627 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_159" "airliner_right_wing_secondary_2" -371.76709 58.653076 -203.60791 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_160" "airliner_right_wing_secondary_2" -306.440674 50.109619 -243.538574 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_161" "airliner_right_wing_secondary_2" -185.939453 35.882568 -152.441406 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_162" "airliner_right_wing_secondary_2" -168.45459 47.605591 -126.269043 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_163" "airliner_right_wing_secondary_2" -191.310059 48.902588 -154.760742 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_164" "airliner_right_wing_secondary_2" 273.189453 6.359192 -1.476563 0 0 0 0 0 0 0 0 0
$definebone "baked_RW_debris_secondary_165" "airliner_right_wing_secondary_2" 205.813477 -14.154297 162.644775 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "airliner_right_wing_secondary_2" position rotation
$bonesaveframe "baked_RW_debris_secondary_101" position rotation
$bonesaveframe "baked_RW_debris_secondary_102" position rotation
$bonesaveframe "baked_RW_debris_secondary_103" position rotation
$bonesaveframe "baked_RW_debris_secondary_104" position rotation
$bonesaveframe "baked_RW_debris_secondary_105" position rotation
$bonesaveframe "baked_RW_debris_secondary_106" position rotation
$bonesaveframe "baked_RW_debris_secondary_107" position rotation
$bonesaveframe "baked_RW_debris_secondary_108" position rotation
$bonesaveframe "baked_RW_debris_secondary_109" position rotation
$bonesaveframe "baked_RW_debris_secondary_110" position rotation
$bonesaveframe "baked_RW_debris_secondary_111" position rotation
$bonesaveframe "baked_RW_debris_secondary_112" position rotation
$bonesaveframe "baked_RW_debris_secondary_113" position rotation
$bonesaveframe "baked_RW_debris_secondary_114" position rotation
$bonesaveframe "baked_RW_debris_secondary_115" position rotation
$bonesaveframe "baked_RW_debris_secondary_116" position rotation
$bonesaveframe "baked_RW_debris_secondary_117" position rotation
$bonesaveframe "baked_RW_debris_secondary_118" position rotation
$bonesaveframe "baked_RW_debris_secondary_119" position rotation
$bonesaveframe "baked_RW_debris_secondary_120" position rotation
$bonesaveframe "baked_RW_debris_secondary_121" position rotation
$bonesaveframe "baked_RW_debris_secondary_122" position rotation
$bonesaveframe "baked_RW_debris_secondary_123" position rotation
$bonesaveframe "baked_RW_debris_secondary_124" position rotation
$bonesaveframe "baked_RW_debris_secondary_125" position rotation
$bonesaveframe "baked_RW_debris_secondary_126" position rotation
$bonesaveframe "baked_RW_debris_secondary_127" position rotation
$bonesaveframe "baked_RW_debris_secondary_128" position rotation
$bonesaveframe "baked_RW_debris_secondary_129" position rotation
$bonesaveframe "baked_RW_debris_secondary_130" position rotation
$bonesaveframe "baked_RW_debris_secondary_131" position rotation
$bonesaveframe "baked_RW_debris_secondary_132" position rotation
$bonesaveframe "baked_RW_debris_secondary_133" position rotation
$bonesaveframe "baked_RW_debris_secondary_134" position rotation
$bonesaveframe "baked_RW_debris_secondary_135" position rotation
$bonesaveframe "baked_RW_debris_secondary_136" position rotation
$bonesaveframe "baked_RW_debris_secondary_137" position rotation
$bonesaveframe "baked_RW_debris_secondary_138" position rotation
$bonesaveframe "baked_RW_debris_secondary_139" position rotation
$bonesaveframe "baked_RW_debris_secondary_140" position rotation
$bonesaveframe "baked_RW_debris_secondary_141" position rotation
$bonesaveframe "baked_RW_debris_secondary_142" position rotation
$bonesaveframe "baked_RW_debris_secondary_143" position rotation
$bonesaveframe "baked_RW_debris_secondary_144" position rotation
$bonesaveframe "baked_RW_debris_secondary_145" position rotation
$bonesaveframe "baked_RW_debris_secondary_146" position rotation
$bonesaveframe "baked_RW_debris_secondary_147" position rotation
$bonesaveframe "baked_RW_debris_secondary_148" position rotation
$bonesaveframe "baked_RW_debris_secondary_149" position rotation
$bonesaveframe "baked_RW_debris_secondary_150" position rotation
$bonesaveframe "baked_RW_debris_secondary_151" position rotation
$bonesaveframe "baked_RW_debris_secondary_152" position rotation
$bonesaveframe "baked_RW_debris_secondary_153" position rotation
$bonesaveframe "baked_RW_debris_secondary_154" position rotation
$bonesaveframe "baked_RW_debris_secondary_155" position rotation
$bonesaveframe "baked_RW_debris_secondary_156" position rotation
$bonesaveframe "baked_RW_debris_secondary_157" position rotation
$bonesaveframe "baked_RW_debris_secondary_158" position rotation
$bonesaveframe "baked_RW_debris_secondary_159" position rotation
$bonesaveframe "baked_RW_debris_secondary_160" position rotation
$bonesaveframe "baked_RW_debris_secondary_161" position rotation
$bonesaveframe "baked_RW_debris_secondary_162" position rotation
$bonesaveframe "baked_RW_debris_secondary_163" position rotation
$bonesaveframe "baked_RW_debris_secondary_164" position rotation
$bonesaveframe "baked_RW_debris_secondary_165" position rotation

$sectionframes 30 597

$sequence "idle" {
	"airliner_right_wing_secondary_2_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "idleOuttaMap" {
	"airliner_right_wing_secondary_2_anims\idleOuttaMap.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "boom" {
	"airliner_right_wing_secondary_2_anims\boom.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
