// Created by Crowbar 0.74

$modelname "v_models/anim_v_smg.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition -1.856 -21.916 -11.719

$cdmaterials "models\v_models\"

$attachment "fowardnode" "ValveBiped.weapon_bone" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox 3.075 -11.036 -21.739 40.757 7.324 -1.698

$definebone "ValveBiped.Bip01_Spine2" "" 3.698241 0 0 0 -0.906992 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 5.70089 0 0 0 28.371668 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 4.065391 1.458947 1.5 -63.87528 -147.035805 50.277504 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 5.50736 -0.000003 0 -19.730431 -44.165482 -79.348295 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 10.9074 0 0.000001 -0.000003 -7.20248 -0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 10.424325 -0.000007 -0.000031 6.507306 7.122669 78.669798 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 2.997272 0.005408 -1.477473 8.213353 -12.990152 11.742422 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 1.510382 0.000001 0 0.955243 -34.37459 0.653402 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.808655 0 0 -10.048532 -17.354256 -3.121074 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 3.30579 0.203112 -0.54673 5.954123 -16.778204 11.337856 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.807177 0 0 -5.063455 -30.512975 -2.9776 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 0.966144 0.000002 0 0.559038 -13.904476 0.138371 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.57151 0.109303 0.40958 3.893596 -14.791073 10.730292 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 2.150655 0.000002 0 -3.092652 -37.967154 -2.410834 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 1.152752 0.000002 0 0.688641 -8.970338 0.10869 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.684093 -0.158702 1.419182 1.961121 -11.693717 10.352716 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.701013 -0.000001 0 3.669056 -38.756252 2.940822 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 0.99471 0.000002 0 2.209331 -1.896546 0.073169 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.068072 -1.287203 0.981903 -19.741842 -7.111207 97.051428 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.836304 0 0 -10.778416 -10.615987 0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 1.223946 0 -0.000003 -2.328836 11.249065 0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Ulna" "ValveBiped.Bip01_L_Forearm" 5.212174 0 0 -0.000003 0 -5.467968 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 10.42435 0 0 -0.000003 0 -10.363949 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 4.065391 1.458947 -1.5 63.87528 -147.035805 -54.583283 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 5.50736 0 -0.000001 22.698467 -42.953728 82.694999 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 10.907396 0 -0.000002 0.000003 -7.202477 0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 10.424301 -0.000004 0.000014 -6.507536 7.122612 -78.876985 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 2.997293 0.000065 1.477481 -8.213407 -12.989927 -11.535191 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 1.510386 -0.000001 0 -0.955233 -34.374607 -0.653401 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.808651 0 0 10.048538 -17.354271 3.121072 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 3.30581 0.201132 0.547461 -5.954235 -16.777986 -11.130628 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.807175 0 0 5.063457 -30.512989 2.977604 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 0.96614 0 0 -0.559038 -13.904483 -0.138368 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.571527 0.110783 -0.409181 -3.893706 -14.790908 -10.523119 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 2.150659 -0.000002 0 3.092654 -37.967167 2.410835 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 1.152751 0.000002 0 -0.688638 -8.970339 -0.108689 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.684117 -0.153568 -1.419746 -1.961177 -11.693496 -10.145484 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.701015 0.000001 0 -3.669047 -38.756245 -2.940821 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 0.994707 0.000002 0 -2.209319 -1.896548 -0.073166 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.068095 -1.283653 -0.986553 19.767268 -7.037123 -96.832985 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.836304 -0.000001 0.000001 10.778428 -10.615994 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 1.223944 0 0 2.328847 11.249042 -0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Ulna" "ValveBiped.Bip01_R_Forearm" 5.212174 0.000001 0 0.000003 0.000003 5.367815 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 10.424347 0 -0.000001 0.000003 0.000003 10.169717 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone" "ValveBiped.Bip01_Spine2" 0 0.744264 2.049373 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_Clip" "ValveBiped.weapon_bone" 0 0.700738 0.401364 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_trigger" "ValveBiped.weapon_bone" 0.016468 3.132728 1.907171 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_forwardassist" "ValveBiped.weapon_bone" -0.011905 5.511323 5.237485 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_door" "ValveBiped.weapon_bone" -1.149073 4.361582 0.46738 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_misc01" "ValveBiped.weapon_bone" 0.829016 4.847685 3.120154 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.strap" "ValveBiped.weapon_bone" 0.015 1.608 6.164001 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32 nostall

$bonesaveframe "ValveBiped.Bip01_Spine2" position
$bonesaveframe "ValveBiped.Bip01_L_Ulna" position
$bonesaveframe "ValveBiped.Bip01_L_Wrist" position
$bonesaveframe "ValveBiped.Bip01_R_Ulna" position
$bonesaveframe "ValveBiped.Bip01_R_Wrist" position
$bonesaveframe "ValveBiped.weapon_bone" position
$bonesaveframe "ValveBiped.weapon_bone_Clip" position
$bonesaveframe "ValveBiped.weapon_bone_forwardassist" position

$sectionframes 30 125

$poseparameter "ver_aims" -1 1 loop 0
$poseparameter "move_x" -1 1 loop 0

$ikchain "rhand" "ValveBiped.Bip01_R_Hand" knee 0.707 0.707 0
$ikchain "lhand" "ValveBiped.Bip01_L_Hand" knee 0.707 0.707 0

$animation "a_smg_arms_trans_down_corrective_animation" "anim_v_smg_anims\a_smg_arms_trans_down_corrective_animation.smd" {
}

$animation "a_smg_arms_trans_corrective_animation" "anim_v_smg_anims\a_smg_arms_trans_corrective_animation.smd" {
}

$animation "a_smg_arms_trans_up_corrective_animation" "anim_v_smg_anims\a_smg_arms_trans_up_corrective_animation.smd" {
}

$animation "anim_smg_pickup_corrective_animation" "anim_v_smg_anims\anim_smg_pickup_corrective_animation.smd" {
}

$animation "anim_smg_pickup_partial_corrective_animation" "anim_v_smg_anims\anim_smg_pickup_partial_corrective_animation.smd" {
}

$animation "anim_smg_pickup_partial2_corrective_animation" "anim_v_smg_anims\anim_smg_pickup_partial2_corrective_animation.smd" {
}

$animation "anim_smg_reload_corrective_animation" "anim_v_smg_anims\anim_smg_reload_corrective_animation.smd" {
}

$animation "anim_smg_reload_clipout_corrective_animation" "anim_v_smg_anims\anim_smg_reload_clipout_corrective_animation.smd" {
}

$animation "anim_smg_reload_empty_corrective_animation" "anim_v_smg_anims\anim_smg_reload_empty_corrective_animation.smd" {
}

$animation "anim_smg_reload_empty_clipout_corrective_animation" "anim_v_smg_anims\anim_smg_reload_empty_clipout_corrective_animation.smd" {
}

$animation "anim_smg_reload_empty_partial_corrective_animation" "anim_v_smg_anims\anim_smg_reload_empty_partial_corrective_animation.smd" {
}

$animation "anim_smg_deploy_corrective_animation" "anim_v_smg_anims\anim_smg_deploy_corrective_animation.smd" {
}

$animation "anim_smg_shoot_corrective_animation" "anim_v_smg_anims\anim_smg_shoot_corrective_animation.smd" {
}

$animation "anim_smg_neutral" "anim_v_smg_anims\anim_smg_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
}

$animation "a_smg_pose_neutral" "anim_v_smg_anims\a_smg_pose_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
}

$animation "a_smg_arms_trans_down" "anim_v_smg_anims\a_smg_arms_trans_down.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_smg_arms_trans_down_corrective_animation" 0
}

$animation "a_smg_arms_trans" "anim_v_smg_anims\a_smg_arms_trans.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_smg_arms_trans_corrective_animation" 0
}

$animation "a_smg_arms_trans_up" "anim_v_smg_anims\a_smg_arms_trans_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_smg_arms_trans_up_corrective_animation" 0
}

$animation "ta_smg_run_trans_idle" "anim_v_smg_anims\ta_smg_run_trans_idle.smd" {
	fps 30
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 160 160 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 160 160 target 0
}

$animation "ta_smg_run_trans_run" "anim_v_smg_anims\ta_smg_run_trans_run.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 0
}

$animation "anim_smg_pickup" "anim_v_smg_anims\anim_smg_pickup.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_pickup_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 165 165 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 165 165 target 0
}

$animation "anim_smg_pickup_partial" "anim_v_smg_anims\anim_smg_pickup_partial.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_pickup_partial_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 102 102 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 102 102 target 0
}

$animation "anim_smg_pickup_partial2" "anim_v_smg_anims\anim_smg_pickup_partial2.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_pickup_partial2_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
}

$animation "anim_smg_reload" "anim_v_smg_anims\anim_smg_reload.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_reload_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 110 110 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 110 110 target 0
}

$animation "anim_smg_reload_clipout" "anim_v_smg_anims\anim_smg_reload_clipout.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_reload_clipout_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 90 90 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 90 90 target 0
}

$animation "anim_smg_reload_empty" "anim_v_smg_anims\anim_smg_reload_empty.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_reload_empty_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 145 145 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 145 145 target 0
}

$animation "anim_smg_reload_empty_clipout" "anim_v_smg_anims\anim_smg_reload_empty_clipout.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_reload_empty_clipout_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 125 125 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 125 125 target 0
}

$animation "anim_smg_reload_empty_partial" "anim_v_smg_anims\anim_smg_reload_empty_partial.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_reload_empty_partial_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 78 78 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 78 78 target 0
}

$animation "anim_smg_deploy" "anim_v_smg_anims\anim_smg_deploy.smd" {
	fps 40
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_deploy_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
}

$animation "anim_smg_shoot" "anim_v_smg_anims\anim_smg_shoot.smd" {
	fps 38
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_smg_shoot_corrective_animation" 0
}

$sequence "a_smg_arms_vaims" {
	"a_smg_arms_trans_down"
	"a_smg_arms_trans"
	"a_smg_arms_trans_up"
	blend "ver_aims" 1 -1
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
}

$sequence "smg_idle" {
	"ta_smg_run_trans_run"
	"ta_smg_run_trans_idle"
	"ta_smg_run_trans_run"
	activity "ACT_VM_IDLE_SMG" 1
	blend "move_x" 1 -1
	blendwidth 3
	fadein 0.2
	fadeout 0.2
	addlayer "a_smg_arms_vaims"
}

$sequence "smg_pickup" {
	"anim_v_smg_anims\smg_pickup.smd"
	activity "ACT_VM_PICKUP_SMG" 1
	{ event AE_PICKUP_CLIPIN 62 "" }
	{ event AE_PICKUP_CHARGING 104 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 144 144 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 144 144 target 1
}

$sequence "smg_pickup_layer" {
	"anim_smg_pickup"
	activity "ACT_VM_PICKUP_SMG_LAYER" 1
	delta
	{ event 5004 31 "SMG.ClipIn" }
	{ event 5004 58 "SMG.ClipLocked" }
	{ event 5004 95 "SMG.SlideBack" }
	{ event 5004 107 "SMG.SlideForward" }
	{ event 5004 133 "SMG.FullAutoButton" }
	{ event AE_PICKUP_CLIPIN 62 "" }
	{ event AE_PICKUP_CHARGING 104 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_pickup_partial" {
	"anim_v_smg_anims\smg_pickup_partial.smd"
	activity "ACT_VM_PICKUP_CLIPIN_SMG" 1
	{ event AE_PICKUP_CHARGING 42 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 82 82 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 82 82 target 1
}

$sequence "smg_pickup_partial_layer" {
	"anim_smg_pickup_partial"
	activity "ACT_VM_PICKUP_CLIPIN_SMG_LAYER" 1
	delta
	{ event 5004 33 "SMG.SlideBack" }
	{ event 5004 44 "SMG.SlideForward" }
	{ event 5004 69 "SMG.FullAutoButton" }
	{ event AE_PICKUP_CHARGING 42 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_pickup_partial2" {
	"anim_v_smg_anims\smg_pickup_partial2.smd"
	activity "ACT_VM_PICKUP_CHARGING_SMG" 1
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 32 32 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 32 32 target 1
}

$sequence "smg_pickup_partial2_layer" {
	"anim_smg_pickup_partial2"
	activity "ACT_VM_PICKUP_CHARGING_SMG_LAYER" 1
	delta
	{ event 5004 17 "SMG.FullAutoButton" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_reload1" {
	"anim_v_smg_anims\smg_reload1.smd"
	activity "ACT_VM_RELOAD_SMG" 1
	{ event AE_RELOAD_CLIPOUT 13 "" }
	{ event AE_RELOAD_CLIPIN 65 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 92 92 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 92 92 target 1
}

$sequence "smg_reload_layer" {
	"anim_smg_reload"
	activity "ACT_VM_RELOAD_SMG_LAYER" 1
	delta
	{ event 5004 13 "SMG.ClipOut" }
	{ event 5004 36 "SMG.ClipIn" }
	{ event 5004 62 "SMG.ClipLocked" }
	{ event AE_RELOAD_CLIPOUT 13 "" }
	{ event AE_RELOAD_CLIPIN 65 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_reload_clipout" {
	"anim_v_smg_anims\smg_reload_clipout.smd"
	activity "ACT_VM_RELOAD_CLIPOUT_SMG" 1
	{ event AE_RELOAD_CLIPIN 45 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 72 72 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 72 72 target 1
}

$sequence "smg_reload_clipout_layer" {
	"anim_smg_reload_clipout"
	activity "ACT_VM_RELOAD_CLIPOUT_SMG_LAYER" 1
	delta
	{ event 5004 16 "SMG.ClipIn" }
	{ event 5004 42 "SMG.ClipLocked" }
	{ event AE_RELOAD_CLIPIN 45 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_reload_empty" {
	"anim_v_smg_anims\smg_reload_empty.smd"
	activity "ACT_VM_RELOAD_EMPTY_SMG" 1
	{ event AE_RELOAD_EMPTY_CLIPOUT 13 "" }
	{ event AE_RELOAD_EMPTY_CLIPIN 65 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 130 130 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 130 130 target 1
}

$sequence "smg_reload_empty_layer" {
	"anim_smg_reload_empty"
	activity "ACT_VM_RELOAD_EMPTY_SMG_LAYER" 1
	delta
	{ event 5004 13 "SMG.ClipOut" }
	{ event 5004 36 "SMG.ClipIn" }
	{ event 5004 62 "SMG.ClipLocked" }
	{ event 5004 100 "SMG.SlideBack" }
	{ event 5004 112 "SMG.SlideForward" }
	{ event AE_RELOAD_EMPTY_CLIPOUT 13 "" }
	{ event AE_RELOAD_EMPTY_CLIPIN 65 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_reload_empty_clipout" {
	"anim_v_smg_anims\smg_reload_empty_clipout.smd"
	activity "ACT_VM_RELOAD_EMPTY_CLIPOUT_SMG" 1
	{ event AE_RELOAD_EMPTY_CLIPIN 45 "" }
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 110 110 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 110 110 target 1
}

$sequence "smg_reload_empty_clipout_layer" {
	"anim_smg_reload_empty_clipout"
	activity "ACT_VM_RELOAD_EMPTY_CLIPOUT_SMG_LAYER" 1
	delta
	{ event 5004 16 "SMG.ClipIn" }
	{ event 5004 42 "SMG.ClipLocked" }
	{ event 5004 80 "SMG.SlideBack" }
	{ event 5004 91 "SMG.SlideForward" }
	{ event AE_RELOAD_EMPTY_CLIPIN 45 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_reload1_empty_partial" {
	"anim_v_smg_anims\smg_reload1_empty_partial.smd"
	activity "ACT_VM_RELOAD_EMPTY_CLIPIN_SMG" 1
	fadein 0.2
	fadeout 0.2
	fps 38
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 63 63 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 63 63 target 1
}

$sequence "smg_reload_empty_partial_layer" {
	"anim_smg_reload_empty_partial"
	activity "ACT_VM_RELOAD_EMPTY_CLIPIN_SMG_LAYER" 1
	delta
	{ event 5004 33 "SMG.SlideBack" }
	{ event 5004 44 "SMG.SlideForward" }
	fadein 0.2
	fadeout 0.2
}

$sequence "smg_deploy" {
	"anim_v_smg_anims\smg_deploy.smd"
	activity "ACT_VM_DEPLOY_SMG" 1
	{ event 5004 1 "SMG.Deploy" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 40
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 47 47 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 47 47 target 1
}

$sequence "smg_deploy_layer" {
	"anim_smg_deploy"
	activity "ACT_VM_DEPLOY_SMG_LAYER" 1
	delta
	{ event 5004 1 "SMG.Deploy" }
	fadein 0
	fadeout 0.6
}

$sequence "smg_shoot1" {
	"anim_v_smg_anims\smg_shoot1.smd"
	activity "ACT_VM_PRIMARYATTACK_SMG" 1
	{ event AE_MUZZLEFLASH 0 "1" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 15 15 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 15 15 target 0
}

$sequence "smg_shoot_layer" {
	"anim_smg_shoot"
	activity "ACT_VM_SHOOT_SMG_LAYER" 1
	delta
	{ event AE_CL_CREATE_PARTICLE_BRASS 0 "weapon_shell_casing_9mm_fp" }
	{ event AE_MUZZLEFLASH 0 "1" }
	fadein 0.1
	fadeout 0.2
}

$sequence "smg_melee" {
	"anim_v_smg_anims\smg_melee.smd"
	activity "ACT_VM_MELEE_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 50
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 1
}

$sequence "smg_melee_layer" {
	"anim_v_smg_anims\smg_melee_layer.smd"
	activity "ACT_VM_MELEE_SMG_LAYER" 1
	fadein 0
	fadeout 0.5
	fps 45
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
}

$sequence "smg_ItemPickup_idle" {
	"anim_v_smg_anims\smg_ItemPickup_idle.smd"
	activity "ACT_VM_ITEMPICKUP_LOOP_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "smg_ItemPickup_idle_layer" {
	"anim_v_smg_anims\smg_ItemPickup_idle_layer.smd"
	activity "ACT_VM_ITEMPICKUP_LOOP_SMG_LAYER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "smg_ItemPickup_extend" {
	"anim_v_smg_anims\smg_ItemPickup_extend.smd"
	activity "ACT_VM_ITEMPICKUP_EXTEND_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "smg_ItemPickup_extend_layer" {
	"anim_v_smg_anims\smg_ItemPickup_extend_layer.smd"
	activity "ACT_VM_ITEMPICKUP_EXTEND_SMG_LAYER" 1
	{ event 5004 1 "SMG.ItemPickupExtend" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}

$sequence "smg_ItemPickup_retract" {
	"anim_v_smg_anims\smg_ItemPickup_retract.smd"
	activity "ACT_VM_ITEMPICKUP_RETRACT_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}

$sequence "smg_ItemPickup_retract_layer" {
	"anim_v_smg_anims\smg_ItemPickup_retract_layer.smd"
	activity "ACT_VM_ITEMPICKUP_RETRACT_SMG_LAYER" 1
	{ event 5004 1 "SMG.ItemPickupRetract" }
	fadein 0
	fadeout 0.4
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "smg_HelpingHand_idle" {
	"anim_v_smg_anims\smg_HelpingHand_idle.smd"
	activity "ACT_VM_HELPINGHAND_LOOP_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "smg_HelpingHand_idle_layer" {
	"anim_v_smg_anims\smg_HelpingHand_idle_layer.smd"
	activity "ACT_VM_HELPINGHAND_LOOP_SMG_LAYER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "smg_HelpingHand_extend" {
	"anim_v_smg_anims\smg_HelpingHand_extend.smd"
	activity "ACT_VM_HELPINGHAND_EXTEND_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "smg_HelpingHand_extend_layer" {
	"anim_v_smg_anims\smg_HelpingHand_extend_layer.smd"
	activity "ACT_VM_HELPINGHAND_EXTEND_SMG_LAYER" 1
	{ event 5004 1 "SMG.HelpingHandExtend" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "smg_HelpingHand_retract" {
	"anim_v_smg_anims\smg_HelpingHand_retract.smd"
	activity "ACT_VM_HELPINGHAND_RETRACT_SMG" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "smg_HelpingHand_retract_layer" {
	"anim_v_smg_anims\smg_HelpingHand_retract_layer.smd"
	activity "ACT_VM_HELPINGHAND_RETRACT_SMG_LAYER" 1
	{ event 5004 1 "SMG.HelpingHandRetract" }
	fadein 0
	fadeout 0.4
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}
