// Created by Crowbar 0.74

$modelname "hybridPhysx/airliner_fuselage_secondary_3.mdl"

$bodygroup "studio"
{
	studio "airliner_fuselage_secondary_3.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0 "baked_fuselage_debris_secondary_251"

$cdmaterials "models\hybridPhysx\"


$cbox 0 0 0 0 0 0

$bbox -2269.723 2138.863 1106.688 -731.039 2241.084 1324.477

$definebone "airliner_fuselage_secondary_3" "" 4749.973633 1023.582642 3875.618652 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_249" "airliner_fuselage_secondary_3" -25.852539 -70.186096 -189.303223 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_250" "airliner_fuselage_secondary_3" 31.677246 106.146606 -211.611328 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_251" "airliner_fuselage_secondary_3" 2.561523 70.019409 -685.527344 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_252" "airliner_fuselage_secondary_3" -1.942871 -27.559998 -685.968506 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_253" "airliner_fuselage_secondary_3" 32.482422 98.369385 -643.257324 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_254" "airliner_fuselage_secondary_3" 28.430664 103.84729 -503.229248 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_255" "airliner_fuselage_secondary_3" 16.116211 102.201538 531.421387 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_256" "airliner_fuselage_secondary_3" -49.953125 0.176086 482.704102 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_257" "airliner_fuselage_secondary_3" -31.106445 -45.797241 637.76709 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_258" "airliner_fuselage_secondary_3" 41.824707 -64.381653 760.119141 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_259" "airliner_fuselage_secondary_3" -45.124023 33.008911 378.912598 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_260" "airliner_fuselage_secondary_3" -46.344727 27.894165 346.854492 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_261" "airliner_fuselage_secondary_3" -24.1875 73.809204 237.431641 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_262" "airliner_fuselage_secondary_3" -21.755859 76.204224 546.916992 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_263" "airliner_fuselage_secondary_3" -38.755859 49.198364 497.425293 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_264" "airliner_fuselage_secondary_3" -47.016602 -20.205322 559.859863 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_265" "airliner_fuselage_secondary_3" -44.308594 -34.483398 577.306152 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_266" "airliner_fuselage_secondary_3" -36.629883 -29.276733 630.540527 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_267" "airliner_fuselage_secondary_3" -26.812012 -30.176392 672.287598 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_268" "airliner_fuselage_secondary_3" -9.877441 -55.512878 697.619629 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_269" "airliner_fuselage_secondary_3" -18.698242 -44.698486 690.160645 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_270" "airliner_fuselage_secondary_3" 23.966797 -64.263184 748.427246 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_271" "airliner_fuselage_secondary_3" 3.077148 -52.196655 739.260254 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_272" "airliner_fuselage_secondary_3" -29.78125 -44.655212 649.667969 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_273" "airliner_fuselage_secondary_3" 11.845703 -63.655457 731.833496 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_274" "airliner_fuselage_secondary_3" 42.041992 -107.183167 475.315918 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_275" "airliner_fuselage_secondary_3" -28.891602 -66.785522 72.841064 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_276" "airliner_fuselage_secondary_3" 33.547852 -105.856506 -266.455566 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_277" "airliner_fuselage_secondary_3" -46.767578 19.454956 -64.726563 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_278" "airliner_fuselage_secondary_3" -49.824219 -3.840576 -147.656738 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_279" "airliner_fuselage_secondary_3" 29.090332 105.419067 -119.3125 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_280" "airliner_fuselage_secondary_3" 2.236328 96.745117 -245.470947 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_281" "airliner_fuselage_secondary_3" 15.914551 102.418213 -337.526855 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_282" "airliner_fuselage_secondary_3" -1.518555 95.136597 -311.363281 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_283" "airliner_fuselage_secondary_3" 11.254883 -97.590576 -317.470947 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_284" "airliner_fuselage_secondary_3" -0.111328 -87.526001 -398.616455 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_285" "airliner_fuselage_secondary_3" 35.517578 -35.966553 -742.472168 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_286" "airliner_fuselage_secondary_3" 43.114258 90.602173 -734.91748 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_287" "airliner_fuselage_secondary_3" -37.793945 44.10376 -480.173828 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_288" "airliner_fuselage_secondary_3" -16.632324 82.055542 -21.646973 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_289" "airliner_fuselage_secondary_3" -12.76709 86.332642 180.101563 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_290" "airliner_fuselage_secondary_3" -36.695801 53.676636 33.960449 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_291" "airliner_fuselage_secondary_3" -40.245117 -48.599365 462.378906 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_292" "airliner_fuselage_secondary_3" -37.917969 -53.792969 376.291504 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_293" "airliner_fuselage_secondary_3" -32.980469 61.143677 464.223145 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_294" "airliner_fuselage_secondary_3" 1.199219 95.794556 236.062988 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_295" "airliner_fuselage_secondary_3" 42.510254 -93.290405 674.655762 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_296" "airliner_fuselage_secondary_3" -25.325684 -69.882141 563.378906 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_297" "airliner_fuselage_secondary_3" 5.808594 -79.62085 665.945801 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_298" "airliner_fuselage_secondary_3" -19.195313 -70.759155 619.790527 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_299" "airliner_fuselage_secondary_3" 24.961914 -103.341248 502.730957 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_300" "airliner_fuselage_secondary_3" 11.057617 -97.731445 515.459473 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_301" "airliner_fuselage_secondary_3" -0.432617 -90.919128 517.007324 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_302" "airliner_fuselage_secondary_3" -3.860352 -88.685059 517.47998 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_303" "airliner_fuselage_secondary_3" -13.327148 -81.650085 515.459473 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_304" "airliner_fuselage_secondary_3" -13.22168 -82.391357 453.837402 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_305" "airliner_fuselage_secondary_3" -10.815918 -84.283691 417.089355 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_306" "airliner_fuselage_secondary_3" 11.002441 -98.156128 405.652832 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_307" "airliner_fuselage_secondary_3" 23.680664 -102.977783 405.311035 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_308" "airliner_fuselage_secondary_3" 43.182617 -107.558533 379.07666 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_309" "airliner_fuselage_secondary_3" -5.200684 -87.928711 295.408691 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_310" "airliner_fuselage_secondary_3" -28.907715 -66.790955 323.657715 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_311" "airliner_fuselage_secondary_3" -40.34082 -48.60376 217.363281 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_312" "airliner_fuselage_secondary_3" 10.997559 100.852295 171.230957 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_313" "airliner_fuselage_secondary_3" -4.470703 93.293091 121.172852 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_314" "airliner_fuselage_secondary_3" -19.446289 78.987427 25.574707 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_315" "airliner_fuselage_secondary_3" 16.078125 102.436157 59.026855 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_316" "airliner_fuselage_secondary_3" -3.432129 93.424927 -80.15332 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_317" "airliner_fuselage_secondary_3" 44.92627 107.691772 1.48291 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_318" "airliner_fuselage_secondary_3" 16.054199 102.438354 -61.597168 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_319" "airliner_fuselage_secondary_3" -39.910645 47.562866 -141.895508 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_320" "airliner_fuselage_secondary_3" -23.081055 75.107666 -73.036133 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_321" "airliner_fuselage_secondary_3" 16.242676 102.454346 -238.689453 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_322" "airliner_fuselage_secondary_3" -19.335449 78.931763 -243.328125 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_323" "airliner_fuselage_secondary_3" -39.274414 48.163574 -216.166504 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_324" "airliner_fuselage_secondary_3" 16.710938 102.595093 -285.401611 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_325" "airliner_fuselage_secondary_3" 30.023926 106.237549 -292.979492 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_326" "airliner_fuselage_secondary_3" -39.272949 -51.086914 -150.432617 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_327" "airliner_fuselage_secondary_3" -46.59668 -33.624207 -162.852051 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_328" "airliner_fuselage_secondary_3" 2.310547 -92.810486 -130.182129 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_329" "airliner_fuselage_secondary_3" 1.395508 -92.232971 23.657715 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_330" "airliner_fuselage_secondary_3" -0.257324 -72.907104 -511.859863 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_331" "airliner_fuselage_secondary_3" -39.528809 -26.872925 -501.485107 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_332" "airliner_fuselage_secondary_3" -20.962891 10.565796 -662.285156 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_333" "airliner_fuselage_secondary_3" -9.289551 1.329346 -718.953613 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_334" "airliner_fuselage_secondary_3" -14.631836 35.619263 -706.666504 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_335" "airliner_fuselage_secondary_3" 48.613281 -108.140015 -242.118652 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_336" "airliner_fuselage_secondary_3" 29.160156 -85.661865 694.696289 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_337" "airliner_fuselage_secondary_3" -28.789551 68.772583 242.028809 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_338" "airliner_fuselage_secondary_3" -35.096191 -44.449219 610.598145 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_339" "airliner_fuselage_secondary_3" -44.142578 -37.392639 267.912598 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_340" "airliner_fuselage_secondary_3" 9.211914 -93.614136 397.433105 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_341" "airliner_fuselage_secondary_3" -46.637695 26.501465 297.01123 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_342" "airliner_fuselage_secondary_3" 38.361816 -106.006348 14.352539 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_343" "airliner_fuselage_secondary_3" 31.396484 -103.678589 -116.261719 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_344" "airliner_fuselage_secondary_3" -48.095703 -18.316162 201.967041 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_345" "airliner_fuselage_secondary_3" -14.712891 -77.533813 171.910645 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_346" "airliner_fuselage_secondary_3" -7.231445 -86.608765 102.919434 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_347" "airliner_fuselage_secondary_3" -23.460938 -72.931396 -228.452148 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_348" "airliner_fuselage_secondary_3" -46.430664 26.420044 -245.71582 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_349" "airliner_fuselage_secondary_3" -34.34082 58.101929 -310.053467 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_350" "airliner_fuselage_secondary_3" 21.227051 102.948486 139.25708 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_351" "airliner_fuselage_secondary_3" -28.365723 -48.442993 -493.438965 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_352" "airliner_fuselage_secondary_3" -33.733887 -55.605591 -381.422363 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_353" "airliner_fuselage_secondary_3" -7.808594 0.219177 -704.568115 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_354" "airliner_fuselage_secondary_3" -19.193359 77.755737 -487.479004 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_355" "airliner_fuselage_secondary_3" 2.489258 82.895874 -645.933594 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_356" "airliner_fuselage_secondary_3" 28.193359 103.876587 -473.786621 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_357" "airliner_fuselage_secondary_3" 39.242188 106.995483 520.804199 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_358" "airliner_fuselage_secondary_3" -44.358398 -32.551025 531.719238 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_359" "airliner_fuselage_secondary_3" -39.169434 47.007202 446.539551 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_360" "airliner_fuselage_secondary_3" -16.172363 82.588013 236.985352 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_361" "airliner_fuselage_secondary_3" -21.603516 74.38855 518.072266 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_362" "airliner_fuselage_secondary_3" -46.483887 26.453735 482.702637 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_363" "airliner_fuselage_secondary_3" -19.391602 -75.387024 432.864746 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_364" "airliner_fuselage_secondary_3" -5.449707 -86.432129 323.929199 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_365" "airliner_fuselage_secondary_3" -22.258789 -74.440186 -261.865234 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_366" "airliner_fuselage_secondary_3" 23.664063 -102.96875 -186.942627 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_367" "airliner_fuselage_secondary_3" -13.736328 -81.319458 -164.171143 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_368" "airliner_fuselage_secondary_3" 44.75293 107.673218 -179.444336 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_369" "airliner_fuselage_secondary_3" 32.204102 -83.159058 -527.991211 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_370" "airliner_fuselage_secondary_3" 18.796875 83.997192 -717.106201 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_371" "airliner_fuselage_secondary_3" -46.643555 6.553345 -491.87085 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_372" "airliner_fuselage_secondary_3" 39.214844 107.139648 -58.26123 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "airliner_fuselage_secondary_3" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_249" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_250" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_251" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_252" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_253" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_254" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_255" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_256" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_257" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_258" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_259" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_260" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_261" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_262" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_263" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_264" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_265" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_266" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_267" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_268" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_269" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_270" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_271" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_272" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_273" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_274" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_275" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_276" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_277" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_278" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_279" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_280" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_281" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_282" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_283" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_284" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_285" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_286" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_287" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_288" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_289" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_290" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_291" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_292" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_293" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_294" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_295" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_296" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_297" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_298" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_299" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_300" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_301" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_302" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_303" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_304" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_305" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_306" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_307" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_308" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_309" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_310" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_311" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_312" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_313" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_314" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_315" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_316" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_317" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_318" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_319" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_320" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_321" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_322" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_323" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_324" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_325" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_326" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_327" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_328" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_329" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_330" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_331" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_332" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_333" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_334" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_335" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_336" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_337" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_338" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_339" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_340" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_341" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_342" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_343" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_344" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_345" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_346" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_347" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_348" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_349" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_350" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_351" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_352" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_353" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_354" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_355" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_356" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_357" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_358" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_359" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_360" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_361" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_362" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_363" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_364" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_365" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_366" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_367" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_368" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_369" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_370" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_371" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_372" position rotation

$sectionframes 30 597

$sequence "idle" {
	"airliner_fuselage_secondary_3_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "idleOuttaMap" {
	"airliner_fuselage_secondary_3_anims\idleOuttaMap.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "boom" {
	"airliner_fuselage_secondary_3_anims\boom.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
