// Created by Crowbar 0.74

$modelname "hybridPhysx/airliner_left_wing_secondary.mdl"

$bodygroup "studio"
{
	studio "airliner_left_wing_secondary.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0 "baked_LW_debris_secondary_24"

$cdmaterials "models\hybridPhysx\"


$cbox 0 0 0 0 0 0

$bbox -1896.098 2278.925 1115.35 -1242.619 3155.339 1255.544

$definebone "airliner_left_wing_secondary" "" 5277.131836 993.446655 3806.641602 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_1" "airliner_left_wing_secondary" 403.724609 61.524536 -317.177002 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_2" "airliner_left_wing_secondary" 410.625 68.33313 -286.275635 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_3" "airliner_left_wing_secondary" 420.455566 62.316528 -280.119629 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_4" "airliner_left_wing_secondary" 387.750977 60.214478 -242.787842 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_5" "airliner_left_wing_secondary" -372.410156 13.973267 20.624023 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_6" "airliner_left_wing_secondary" -398.041504 -50.243042 13.902588 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_7" "airliner_left_wing_secondary" -402.625977 -51.079224 -77.382324 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_8" "airliner_left_wing_secondary" -354.246094 -26.095215 -6.631348 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_9" "airliner_left_wing_secondary" -203.65625 -8.034851 68.165039 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_10" "airliner_left_wing_secondary" -259.264648 -18.17041 163.064453 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_11" "airliner_left_wing_secondary" -372.84668 4.770386 -40.346924 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_12" "airliner_left_wing_secondary" -312.991211 7.635193 55.489746 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_13" "airliner_left_wing_secondary" -312.15625 -22.560791 152.634766 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_14" "airliner_left_wing_secondary" -256.704102 -14.576904 193.134766 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_15" "airliner_left_wing_secondary" -283.680176 -18.168335 124.876221 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_16" "airliner_left_wing_secondary" -170.219727 20.314331 90.868652 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_17" "airliner_left_wing_secondary" -150.664063 12.914673 -64.327637 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_18" "airliner_left_wing_secondary" -150.189453 -4.725891 88.896484 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_19" "airliner_left_wing_secondary" -146.275879 9.279846 111.160156 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_20" "airliner_left_wing_secondary" -164.209961 20.28479 23.0271 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_22" "airliner_left_wing_secondary" -373.493652 25.209961 174.902344 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_23" "airliner_left_wing_secondary" -366.956055 20.188232 126.653809 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_24" "airliner_left_wing_secondary" -386.032715 -24.818115 306.157227 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_25" "airliner_left_wing_secondary" -411.428711 -58.639343 256.959473 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_26" "airliner_left_wing_secondary" -277.475586 11.424805 171.117676 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_27" "airliner_left_wing_secondary" -298.490723 -14.315491 55.646973 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_28" "airliner_left_wing_secondary" 201.650879 39.086548 -186.905029 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_29" "airliner_left_wing_secondary" 196.402344 35.901001 -124.83374 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_30" "airliner_left_wing_secondary" 189.803711 35.303101 -147.732422 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_31" "airliner_left_wing_secondary" 215.036133 49.608887 -201.869385 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_32" "airliner_left_wing_secondary" 185.800781 47.683472 -126.443359 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_33" "airliner_left_wing_secondary" 415.050781 68.239136 -274.039551 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_34" "airliner_left_wing_secondary" 393.267578 59.328613 -289.286621 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_35" "airliner_left_wing_secondary" 420.853516 63.918335 -267.800781 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_36" "airliner_left_wing_secondary" 386.063965 64.936035 -288.007324 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_37" "airliner_left_wing_secondary" 392.121582 59.891235 -300.312988 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_38" "airliner_left_wing_secondary" 414.384766 61.330566 -292.703125 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_39" "airliner_left_wing_secondary" 433.014648 66.86853 -278.519287 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_40" "airliner_left_wing_secondary" 385.888672 65.639038 -278.650879 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_41" "airliner_left_wing_secondary" 423.606445 66.572266 -276.885742 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_42" "airliner_left_wing_secondary" 391.087402 63.967285 -308.977783 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_43" "airliner_left_wing_secondary" 390.121094 64.822388 -250.359131 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_44" "airliner_left_wing_secondary" 180.365234 33.056763 -117.582031 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_45" "airliner_left_wing_secondary" 203.066406 36.008423 -146.120361 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_46" "airliner_left_wing_secondary" 197.45459 38.505737 -114.77002 0 0 -0.000057 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_47" "airliner_left_wing_secondary" 207.499023 36.50769 -129.568359 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_48" "airliner_left_wing_secondary" 195.500977 37.665894 -169.160645 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_49" "airliner_left_wing_secondary" 182.911621 34.113037 -135.185303 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_50" "airliner_left_wing_secondary" 194.529297 48.903442 -176.403564 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_51" "airliner_left_wing_secondary" 215.705078 41.798218 -215.025879 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_52" "airliner_left_wing_secondary" 186.178711 41.177734 -111.736816 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_53" "airliner_left_wing_secondary" 173.193359 32.174683 -107.780518 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_54" "airliner_left_wing_secondary" 202.687012 40.443481 -209.220703 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_55" "airliner_left_wing_secondary" 215.050293 40.153931 -187.402588 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_56" "airliner_left_wing_secondary" 181.806152 35.846558 -158.216309 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_57" "airliner_left_wing_secondary" 207.484375 50.94165 -166.496582 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_58" "airliner_left_wing_secondary" 225.052734 42.758301 -238.703369 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_59" "airliner_left_wing_secondary" 206.362793 47.414185 -134.262207 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_60" "airliner_left_wing_secondary" 216.793945 47.70105 -222.094238 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_61" "airliner_left_wing_secondary" 178.697266 34.037476 -109.331787 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_62" "airliner_left_wing_secondary" -417.257813 -59.56604 -3.07373 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_63" "airliner_left_wing_secondary" -274.95752 12.287109 63.643799 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_64" "airliner_left_wing_secondary" -216.992188 18.146118 70.830566 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_65" "airliner_left_wing_secondary" -130.433594 11.922119 96.076416 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_66" "airliner_left_wing_secondary" -180.702148 17.767212 13.9104 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_67" "airliner_left_wing_secondary" -372.535156 9.531799 -2.223633 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_68" "airliner_left_wing_secondary" -405.753906 -47.44104 309.12207 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_69" "airliner_left_wing_secondary" -204.341797 -5.389099 44.193359 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_70" "airliner_left_wing_secondary" -187.820313 -8.242554 86.523926 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_71" "airliner_left_wing_secondary" -167.583008 -4.017395 57.011963 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_72" "airliner_left_wing_secondary" -247.105469 -9.926392 68.30542 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_73" "airliner_left_wing_secondary" -164.707031 -0.855835 22.564209 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_74" "airliner_left_wing_secondary" -270.714844 -13.60376 80.174805 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_75" "airliner_left_wing_secondary" -140.798828 -1.756409 103.783691 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_76" "airliner_left_wing_secondary" -323.419434 -17.149658 20.396484 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_77" "airliner_left_wing_secondary" -318.212891 11.557739 97.075195 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_78" "airliner_left_wing_secondary" -305.791992 13.188599 143.398926 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_79" "airliner_left_wing_secondary" -245.117188 14.986206 68.224121 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_80" "airliner_left_wing_secondary" -143.880859 -1.965942 55.048828 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_81" "airliner_left_wing_secondary" -155.623047 19.007446 100.056885 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_82" "airliner_left_wing_secondary" -177.625488 20.558472 59.82666 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_83" "airliner_left_wing_secondary" -162.531738 16.439453 -22.008789 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_84" "airliner_left_wing_secondary" -117.787598 4.641602 99.80127 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_85" "airliner_left_wing_secondary" -172.207031 -1.525452 8.615723 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_86" "airliner_left_wing_secondary" -286.900391 -21.701172 190.747559 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_87" "airliner_left_wing_secondary" -256.270508 -1.904846 194.473389 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_88" "airliner_left_wing_secondary" -279.319336 -16.802124 108.207031 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_89" "airliner_left_wing_secondary" -248.206543 -11.91687 82.074219 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_90" "airliner_left_wing_secondary" -176.945313 -7.29187 85.839844 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_91" "airliner_left_wing_secondary" -167.809082 0.07428 -12.886719 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_92" "airliner_left_wing_secondary" -144.013672 -3.40918 61.725342 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_93" "airliner_left_wing_secondary" -302.229492 -19.633606 135.127441 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_94" "airliner_left_wing_secondary" -282.619141 -3.268921 187.102295 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_95" "airliner_left_wing_secondary" -314.114746 3.429871 13.516602 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_96" "airliner_left_wing_secondary" -291.702148 12.759949 96.020508 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_97" "airliner_left_wing_secondary" -283.755859 -20.727295 162.39209 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_98" "airliner_left_wing_secondary" -372.139648 15.300293 50.263428 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_99" "airliner_left_wing_secondary" -365.081055 0.759705 -14.806885 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_100" "airliner_left_wing_secondary" -335.844727 12.182007 122.51416 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_101" "airliner_left_wing_secondary" -369.350098 17.985657 89.837891 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_102" "airliner_left_wing_secondary" -337.405273 1.438293 4.988281 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_103" "airliner_left_wing_secondary" -374.292969 3.118164 -67.97168 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_104" "airliner_left_wing_secondary" -372.741699 8.014404 -18.713135 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_105" "airliner_left_wing_secondary" -368.152832 10.234009 25.05249 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_106" "airliner_left_wing_secondary" -369.416016 16.817261 60.526611 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_107" "airliner_left_wing_secondary" -367.571777 16.449646 99.981689 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_108" "airliner_left_wing_secondary" -372.53125 23.343872 125.272217 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_109" "airliner_left_wing_secondary" -366.343262 16.978271 142.675537 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_110" "airliner_left_wing_secondary" -366.975586 20.200562 216.711426 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_111" "airliner_left_wing_secondary" -373.49707 24.130432 151.935547 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_112" "airliner_left_wing_secondary" -372.918945 15.058594 258.489258 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_113" "airliner_left_wing_secondary" -409.821289 -57.886841 182.134766 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_114" "airliner_left_wing_secondary" -404.40918 -47.493408 285.053711 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_115" "airliner_left_wing_secondary" -376.216797 0.572021 284.317871 0 -0.000057 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_116" "airliner_left_wing_secondary" -394.177734 -42.950867 -129.351318 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_117" "airliner_left_wing_secondary" -413.782227 -57.84259 -47.263916 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_118" "airliner_left_wing_secondary" -407.554199 -54.605835 70.669434 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_119" "airliner_left_wing_secondary" -392.084961 -31.824829 -161.45752 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_120" "airliner_left_wing_secondary" -388.25293 -44.121094 -36.272461 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_121" "airliner_left_wing_secondary" -417.787109 -58.549683 -98.771729 0 0 0 0 0 0 0 0 0
$definebone "baked_LW_debris_secondary_122" "airliner_left_wing_secondary" -147.626953 -0.914551 41.231934 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "airliner_left_wing_secondary" position rotation
$bonesaveframe "baked_LW_debris_secondary_1" position rotation
$bonesaveframe "baked_LW_debris_secondary_2" position rotation
$bonesaveframe "baked_LW_debris_secondary_3" position rotation
$bonesaveframe "baked_LW_debris_secondary_4" position rotation
$bonesaveframe "baked_LW_debris_secondary_5" position rotation
$bonesaveframe "baked_LW_debris_secondary_6" position rotation
$bonesaveframe "baked_LW_debris_secondary_7" position rotation
$bonesaveframe "baked_LW_debris_secondary_8" position rotation
$bonesaveframe "baked_LW_debris_secondary_9" position rotation
$bonesaveframe "baked_LW_debris_secondary_10" position rotation
$bonesaveframe "baked_LW_debris_secondary_11" position rotation
$bonesaveframe "baked_LW_debris_secondary_12" position rotation
$bonesaveframe "baked_LW_debris_secondary_13" position rotation
$bonesaveframe "baked_LW_debris_secondary_14" position rotation
$bonesaveframe "baked_LW_debris_secondary_15" position rotation
$bonesaveframe "baked_LW_debris_secondary_16" position rotation
$bonesaveframe "baked_LW_debris_secondary_17" position rotation
$bonesaveframe "baked_LW_debris_secondary_18" position rotation
$bonesaveframe "baked_LW_debris_secondary_19" position rotation
$bonesaveframe "baked_LW_debris_secondary_20" position rotation
$bonesaveframe "baked_LW_debris_secondary_22" position rotation
$bonesaveframe "baked_LW_debris_secondary_23" position rotation
$bonesaveframe "baked_LW_debris_secondary_24" position rotation
$bonesaveframe "baked_LW_debris_secondary_25" position rotation
$bonesaveframe "baked_LW_debris_secondary_26" position rotation
$bonesaveframe "baked_LW_debris_secondary_27" position rotation
$bonesaveframe "baked_LW_debris_secondary_28" position rotation
$bonesaveframe "baked_LW_debris_secondary_29" position rotation
$bonesaveframe "baked_LW_debris_secondary_30" position rotation
$bonesaveframe "baked_LW_debris_secondary_31" position rotation
$bonesaveframe "baked_LW_debris_secondary_32" position rotation
$bonesaveframe "baked_LW_debris_secondary_33" position rotation
$bonesaveframe "baked_LW_debris_secondary_34" position rotation
$bonesaveframe "baked_LW_debris_secondary_35" position rotation
$bonesaveframe "baked_LW_debris_secondary_36" position rotation
$bonesaveframe "baked_LW_debris_secondary_37" position rotation
$bonesaveframe "baked_LW_debris_secondary_38" position rotation
$bonesaveframe "baked_LW_debris_secondary_39" position rotation
$bonesaveframe "baked_LW_debris_secondary_40" position rotation
$bonesaveframe "baked_LW_debris_secondary_41" position rotation
$bonesaveframe "baked_LW_debris_secondary_42" position rotation
$bonesaveframe "baked_LW_debris_secondary_43" position rotation
$bonesaveframe "baked_LW_debris_secondary_44" position rotation
$bonesaveframe "baked_LW_debris_secondary_45" position rotation
$bonesaveframe "baked_LW_debris_secondary_46" position rotation
$bonesaveframe "baked_LW_debris_secondary_47" position rotation
$bonesaveframe "baked_LW_debris_secondary_48" position rotation
$bonesaveframe "baked_LW_debris_secondary_49" position rotation
$bonesaveframe "baked_LW_debris_secondary_50" position rotation
$bonesaveframe "baked_LW_debris_secondary_51" position rotation
$bonesaveframe "baked_LW_debris_secondary_52" position rotation
$bonesaveframe "baked_LW_debris_secondary_53" position rotation
$bonesaveframe "baked_LW_debris_secondary_54" position rotation
$bonesaveframe "baked_LW_debris_secondary_55" position rotation
$bonesaveframe "baked_LW_debris_secondary_56" position rotation
$bonesaveframe "baked_LW_debris_secondary_57" position rotation
$bonesaveframe "baked_LW_debris_secondary_58" position rotation
$bonesaveframe "baked_LW_debris_secondary_59" position rotation
$bonesaveframe "baked_LW_debris_secondary_60" position rotation
$bonesaveframe "baked_LW_debris_secondary_61" position rotation
$bonesaveframe "baked_LW_debris_secondary_62" position rotation
$bonesaveframe "baked_LW_debris_secondary_63" position rotation
$bonesaveframe "baked_LW_debris_secondary_64" position rotation
$bonesaveframe "baked_LW_debris_secondary_65" position rotation
$bonesaveframe "baked_LW_debris_secondary_66" position rotation
$bonesaveframe "baked_LW_debris_secondary_67" position rotation
$bonesaveframe "baked_LW_debris_secondary_68" position rotation
$bonesaveframe "baked_LW_debris_secondary_69" position rotation
$bonesaveframe "baked_LW_debris_secondary_70" position rotation
$bonesaveframe "baked_LW_debris_secondary_71" position rotation
$bonesaveframe "baked_LW_debris_secondary_72" position rotation
$bonesaveframe "baked_LW_debris_secondary_73" position rotation
$bonesaveframe "baked_LW_debris_secondary_74" position rotation
$bonesaveframe "baked_LW_debris_secondary_75" position rotation
$bonesaveframe "baked_LW_debris_secondary_76" position rotation
$bonesaveframe "baked_LW_debris_secondary_77" position rotation
$bonesaveframe "baked_LW_debris_secondary_78" position rotation
$bonesaveframe "baked_LW_debris_secondary_79" position rotation
$bonesaveframe "baked_LW_debris_secondary_80" position rotation
$bonesaveframe "baked_LW_debris_secondary_81" position rotation
$bonesaveframe "baked_LW_debris_secondary_82" position rotation
$bonesaveframe "baked_LW_debris_secondary_83" position rotation
$bonesaveframe "baked_LW_debris_secondary_84" position rotation
$bonesaveframe "baked_LW_debris_secondary_85" position rotation
$bonesaveframe "baked_LW_debris_secondary_86" position rotation
$bonesaveframe "baked_LW_debris_secondary_87" position rotation
$bonesaveframe "baked_LW_debris_secondary_88" position rotation
$bonesaveframe "baked_LW_debris_secondary_89" position rotation
$bonesaveframe "baked_LW_debris_secondary_90" position rotation
$bonesaveframe "baked_LW_debris_secondary_91" position rotation
$bonesaveframe "baked_LW_debris_secondary_92" position rotation
$bonesaveframe "baked_LW_debris_secondary_93" position rotation
$bonesaveframe "baked_LW_debris_secondary_94" position rotation
$bonesaveframe "baked_LW_debris_secondary_95" position rotation
$bonesaveframe "baked_LW_debris_secondary_96" position rotation
$bonesaveframe "baked_LW_debris_secondary_97" position rotation
$bonesaveframe "baked_LW_debris_secondary_98" position rotation
$bonesaveframe "baked_LW_debris_secondary_99" position rotation
$bonesaveframe "baked_LW_debris_secondary_100" position rotation
$bonesaveframe "baked_LW_debris_secondary_101" position rotation
$bonesaveframe "baked_LW_debris_secondary_102" position rotation
$bonesaveframe "baked_LW_debris_secondary_103" position rotation
$bonesaveframe "baked_LW_debris_secondary_104" position rotation
$bonesaveframe "baked_LW_debris_secondary_105" position rotation
$bonesaveframe "baked_LW_debris_secondary_106" position rotation
$bonesaveframe "baked_LW_debris_secondary_107" position rotation
$bonesaveframe "baked_LW_debris_secondary_108" position rotation
$bonesaveframe "baked_LW_debris_secondary_109" position rotation
$bonesaveframe "baked_LW_debris_secondary_110" position rotation
$bonesaveframe "baked_LW_debris_secondary_111" position rotation
$bonesaveframe "baked_LW_debris_secondary_112" position rotation
$bonesaveframe "baked_LW_debris_secondary_113" position rotation
$bonesaveframe "baked_LW_debris_secondary_114" position rotation
$bonesaveframe "baked_LW_debris_secondary_115" position rotation
$bonesaveframe "baked_LW_debris_secondary_116" position rotation
$bonesaveframe "baked_LW_debris_secondary_117" position rotation
$bonesaveframe "baked_LW_debris_secondary_118" position rotation
$bonesaveframe "baked_LW_debris_secondary_119" position rotation
$bonesaveframe "baked_LW_debris_secondary_120" position rotation
$bonesaveframe "baked_LW_debris_secondary_121" position rotation
$bonesaveframe "baked_LW_debris_secondary_122" position rotation

$sectionframes 30 597

$sequence "idle" {
	"airliner_left_wing_secondary_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "idleOuttaMap" {
	"airliner_left_wing_secondary_anims\idleOuttaMap.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "boom" {
	"airliner_left_wing_secondary_anims\boom.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
