// Created by Crowbar 0.74

$modelname "hybridPhysx/airliner_fuselage_secondary_2.mdl"

$bodygroup "studio"
{
	studio "airliner_fuselage_secondary_2.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0 "baked_fuselage_debris_secondary_174"

$cdmaterials "models\hybridPhysx\"


$cbox 0 0 0 0 0 0

$bbox -2269.726 2139.037 1106.764 -731.047 2343.413 1324.477

$definebone "airliner_fuselage_secondary_2" "" 4801.224609 1023.620483 3875.61377 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_125" "airliner_fuselage_secondary_2" 27.045898 -103.152344 -230.85791 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_126" "airliner_fuselage_secondary_2" 74.544434 -72.541382 16.496582 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_127" "airliner_fuselage_secondary_2" 91.141113 -48.625366 100.960449 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_128" "airliner_fuselage_secondary_2" 93.291016 41.919189 -64.298828 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_129" "airliner_fuselage_secondary_2" 11.545898 107.100464 49.536133 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_130" "airliner_fuselage_secondary_2" 11.564453 107.101807 -64.651367 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_131" "airliner_fuselage_secondary_2" 58.379883 -64.957764 -479.23291 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_132" "airliner_fuselage_secondary_2" 48.166504 -14.07251 -743.119629 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_133" "airliner_fuselage_secondary_2" 90.519043 40.073853 527.669434 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_134" "airliner_fuselage_secondary_2" 34.698242 102.378418 430.397949 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_135" "airliner_fuselage_secondary_2" 99.039551 12.801514 455.044434 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_136" "airliner_fuselage_secondary_2" 76.948242 70.143433 369.52002 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_137" "airliner_fuselage_secondary_2" 89.706055 -48.504333 475.319336 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_138" "airliner_fuselage_secondary_2" 53.166016 -89.796692 414.933105 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_139" "airliner_fuselage_secondary_2" 49.388184 -91.237549 565.878418 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_140" "airliner_fuselage_secondary_2" 42.074219 -79.765686 672.289551 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_141" "airliner_fuselage_secondary_2" 57.211914 -85.349548 180.534424 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_142" "airliner_fuselage_secondary_2" 75.026855 -72.019165 229.708984 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_143" "airliner_fuselage_secondary_2" 53.179688 -89.788574 67.506836 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_144" "airliner_fuselage_secondary_2" 97.4375 23.69751 216.368652 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_145" "airliner_fuselage_secondary_2" 76.526367 72.089722 313.23877 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_146" "airliner_fuselage_secondary_2" 70.253906 78.953857 88.727539 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_147" "airliner_fuselage_secondary_2" 8.037109 107.444214 161.719727 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_148" "airliner_fuselage_secondary_2" 67.867188 81.543335 206.559082 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_149" "airliner_fuselage_secondary_2" 88.246582 -52.007324 -56.410156 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_150" "airliner_fuselage_secondary_2" 83.058594 -54.784485 -179.523926 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_151" "airliner_fuselage_secondary_2" 61.447266 -83.1427 -211.267822 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_152" "airliner_fuselage_secondary_2" 40.456055 -96.607056 -129.308105 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_153" "airliner_fuselage_secondary_2" 98.355469 23.144165 -74.17749 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_154" "airliner_fuselage_secondary_2" 85.332031 58.241821 -61.361816 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_155" "airliner_fuselage_secondary_2" 50.420898 95.484009 -200.10376 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_156" "airliner_fuselage_secondary_2" 96.60498 29.439331 -193.318604 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_157" "airliner_fuselage_secondary_2" 76.729004 70.368042 -216.469971 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_158" "airliner_fuselage_secondary_2" 99.90625 15.08313 -220.401855 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_159" "airliner_fuselage_secondary_2" 41.723633 98.244263 -327.492432 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_160" "airliner_fuselage_secondary_2" 11.26709 107.104614 -499.349121 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_161" "airliner_fuselage_secondary_2" 73.051758 76.146606 -335.217773 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_162" "airliner_fuselage_secondary_2" 97.859375 26.302368 -342.68457 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_163" "airliner_fuselage_secondary_2" 97.025391 -33.587402 -421.299316 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_164" "airliner_fuselage_secondary_2" 64.257813 -83.053406 -323.578613 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_165" "airliner_fuselage_secondary_2" 90.897461 21.599243 -539.074219 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_166" "airliner_fuselage_secondary_2" 96.958008 28.237671 61.70459 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_167" "airliner_fuselage_secondary_2" 90.09082 -50.737671 -272.246582 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_168" "airliner_fuselage_secondary_2" 99.365234 -24.558716 -357.406982 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_169" "airliner_fuselage_secondary_2" 50.72998 58.802368 -744.958008 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_170" "airliner_fuselage_secondary_2" 26.5 82.562622 -737.458496 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_171" "airliner_fuselage_secondary_2" 67.680176 -54.636841 661.446777 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_172" "airliner_fuselage_secondary_2" 18.053711 -82.53418 707.560059 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_173" "airliner_fuselage_secondary_2" 56.038086 -74.679688 636.309082 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_174" "airliner_fuselage_secondary_2" 91.113281 -18.042847 604.592285 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_175" "airliner_fuselage_secondary_2" 81.967773 -2.347534 671.102051 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_176" "airliner_fuselage_secondary_2" 39.743164 -73.894409 712.127441 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_177" "airliner_fuselage_secondary_2" 28.616211 -97.430054 528.350098 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_178" "airliner_fuselage_secondary_2" 19.329102 -103.761597 433.842773 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_179" "airliner_fuselage_secondary_2" 27.369629 -98.591614 379.730957 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_180" "airliner_fuselage_secondary_2" 93.817383 -25.525635 553.025879 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_181" "airliner_fuselage_secondary_2" 57.665039 -81.351929 604.606934 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_182" "airliner_fuselage_secondary_2" 95.117676 30.805786 566.44873 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_183" "airliner_fuselage_secondary_2" 65.100586 -79.742493 332.137207 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_184" "airliner_fuselage_secondary_2" 59.952148 87.022095 419.717285 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_185" "airliner_fuselage_secondary_2" 55.921875 91.25415 510.047363 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_186" "airliner_fuselage_secondary_2" 82.984375 60.822998 272.309082 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_187" "airliner_fuselage_secondary_2" 29.127441 -102.348389 190.506348 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_188" "airliner_fuselage_secondary_2" 93.404785 -32.719421 220.828613 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_189" "airliner_fuselage_secondary_2" 98.886719 -24.929138 84.637207 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_190" "airliner_fuselage_secondary_2" 8.46582 107.366333 467.050293 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_191" "airliner_fuselage_secondary_2" 26.773926 104.842651 448.132813 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_192" "airliner_fuselage_secondary_2" 95.826172 28.337524 484.556152 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_193" "airliner_fuselage_secondary_2" 72.926758 75.73645 513.179199 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_194" "airliner_fuselage_secondary_2" 76.586914 -70.243652 430.600098 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_195" "airliner_fuselage_secondary_2" 55.441406 -88.293335 435.596191 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_196" "airliner_fuselage_secondary_2" 50.299805 -91.66687 262.869629 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_197" "airliner_fuselage_secondary_2" 7.583008 -107.59967 258.018066 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_198" "airliner_fuselage_secondary_2" 66.930664 -77.366699 204.194092 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_199" "airliner_fuselage_secondary_2" 53.182617 -89.796448 152.389648 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_200" "airliner_fuselage_secondary_2" 76.624023 -70.238037 78.870117 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_201" "airliner_fuselage_secondary_2" 29.80957 99.420776 217.413574 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_202" "airliner_fuselage_secondary_2" 89.269531 -52.473633 272.311035 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_203" "airliner_fuselage_secondary_2" 99.750977 -17.299683 278.268066 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_204" "airliner_fuselage_secondary_2" 100.793945 3.02771 278.260254 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_205" "airliner_fuselage_secondary_2" 83.708008 56.876587 210.609375 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_206" "airliner_fuselage_secondary_2" 34.687012 102.39856 278.317871 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_207" "airliner_fuselage_secondary_2" 51.280762 95.234741 343.102051 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_208" "airliner_fuselage_secondary_2" 75.942383 71.246948 344.626465 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_209" "airliner_fuselage_secondary_2" 97.606445 25.798462 354 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_210" "airliner_fuselage_secondary_2" 100.87207 2.556396 361.060059 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_211" "airliner_fuselage_secondary_2" 97.836914 -28.948486 358.968262 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_212" "airliner_fuselage_secondary_2" 89.943848 -51.183044 341.299805 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_213" "airliner_fuselage_secondary_2" 90.302734 -50.375488 164.521484 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_214" "airliner_fuselage_secondary_2" 90.749512 40.233032 78.959717 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_215" "airliner_fuselage_secondary_2" 29.824219 99.420776 106.094238 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_216" "airliner_fuselage_secondary_2" 93.378906 -36.452515 7.979492 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_217" "airliner_fuselage_secondary_2" -19.791016 -103.597534 553.26123 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_218" "airliner_fuselage_secondary_2" -37.658691 -57.875244 746.467285 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_219" "airliner_fuselage_secondary_2" -59.331055 -42.96167 726.748047 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_220" "airliner_fuselage_secondary_2" -68.801758 -78.5 484.404785 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_221" "airliner_fuselage_secondary_2" -100.081055 -17.453979 462.690918 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_222" "airliner_fuselage_secondary_2" -78.964844 -68.133911 408.176758 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_223" "airliner_fuselage_secondary_2" -96.391113 -31.32074 343.570801 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_224" "airliner_fuselage_secondary_2" -100.706543 10.413696 438.862793 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_225" "airliner_fuselage_secondary_2" -62.741699 87.505371 494.702637 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_226" "airliner_fuselage_secondary_2" -91.015137 47.516235 418.276855 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_227" "airliner_fuselage_secondary_2" -100.705078 12.743286 380.817871 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_228" "airliner_fuselage_secondary_2" -87.978027 53.640991 241.787109 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_229" "airliner_fuselage_secondary_2" -12.020508 107.101196 252.662598 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_230" "airliner_fuselage_secondary_2" -35.124023 102.248901 505.66748 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_231" "airliner_fuselage_secondary_2" -31.163086 -101.842285 19.81543 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_232" "airliner_fuselage_secondary_2" -8.077148 -107.585205 -51.104004 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_233" "airliner_fuselage_secondary_2" -44.697266 -94.444397 -175.32666 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_234" "airliner_fuselage_secondary_2" -30.726563 -101.155029 -237.293701 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_235" "airliner_fuselage_secondary_2" -14.154297 -87.76886 -521.766357 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_236" "airliner_fuselage_secondary_2" -14.162598 -47.235168 -689.131836 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_237" "airliner_fuselage_secondary_2" -99.285645 -24.955933 -23.912109 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_238" "airliner_fuselage_secondary_2" -62.351563 -83.473267 229.365234 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_239" "airliner_fuselage_secondary_2" -86.926758 -50.871704 133.664551 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_240" "airliner_fuselage_secondary_2" -77.052734 -70.267212 -36.744629 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_241" "airliner_fuselage_secondary_2" -69.589844 -77.251465 10.498047 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_242" "airliner_fuselage_secondary_2" -98.175293 13.678833 155.470703 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_243" "airliner_fuselage_secondary_2" -98.13916 13.673828 217.368652 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_244" "airliner_fuselage_secondary_2" -85.507813 58.745483 164.709717 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_245" "airliner_fuselage_secondary_2" -91.229492 40.237915 109.46875 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_246" "airliner_fuselage_secondary_2" -101.226563 3.014282 -1.578369 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_247" "airliner_fuselage_secondary_2" -69.239746 -78.241577 -111.678223 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_248" "airliner_fuselage_secondary_2" -78.952148 -68.220947 -88.778076 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "airliner_fuselage_secondary_2" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_125" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_126" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_127" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_128" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_129" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_130" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_131" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_132" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_133" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_134" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_135" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_136" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_137" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_138" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_139" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_140" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_141" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_142" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_143" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_144" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_145" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_146" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_147" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_148" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_149" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_150" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_151" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_152" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_153" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_154" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_155" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_156" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_157" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_158" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_159" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_160" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_161" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_162" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_163" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_164" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_165" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_166" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_167" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_168" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_169" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_170" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_171" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_172" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_173" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_174" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_175" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_176" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_177" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_178" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_179" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_180" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_181" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_182" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_183" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_184" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_185" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_186" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_187" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_188" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_189" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_190" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_191" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_192" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_193" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_194" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_195" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_196" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_197" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_198" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_199" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_200" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_201" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_202" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_203" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_204" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_205" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_206" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_207" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_208" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_209" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_210" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_211" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_212" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_213" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_214" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_215" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_216" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_217" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_218" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_219" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_220" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_221" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_222" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_223" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_224" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_225" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_226" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_227" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_228" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_229" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_230" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_231" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_232" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_233" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_234" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_235" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_236" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_237" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_238" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_239" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_240" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_241" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_242" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_243" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_244" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_245" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_246" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_247" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_248" position rotation

$sectionframes 30 597

$sequence "idle" {
	"airliner_fuselage_secondary_2_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "idleOuttaMap" {
	"airliner_fuselage_secondary_2_anims\idleOuttaMap.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "boom" {
	"airliner_fuselage_secondary_2_anims\boom.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
