// Created by Crowbar 0.74

$modelname "infected/common_female_tanktop_jeans_rain.mdl"

/* $model "Associates" "Sanae_body.smd" {

	mouth 0 "mouth" "ValveBiped.Bip01_Head1" 0 1 0

	flexfile "common_female_tanktop_jeans_rain_01.vta" 
	{
		defaultflex frame 0
		flex "mouth_a" frame 1
		flex "mouth_i" frame 2
		flex "mouth_u" frame 3
		flex "mouth_e" frame 4
		flex "mouth_o" frame 5
		flex "mouth_wa" frame 6
		flex "mouth_unhappy" frame 7
		flex "mouth_triangle" frame 8
		flex "mouth_triangle2" frame 9
		flex "mouth_meow" frame 10
		flex "mouth_meow2" frame 11
		flex "mouth_smile" frame 12
		flex "mouth_wow" frame 13
		flex "mouth_tongue" frame 14
		flex "mouth_tongue2" frame 15
		flex "mouth_gasp" frame 16
		flex "mouth_grin" frame 17
		flex "mouth_ehh" frame 18
		flex "face_bigger" frame 19
		flex "mouth_up" frame 20
		flex "mouth_down" frame 21
		flex "tongue_thin" frame 22
		flex "tongue_thick" frame 23
		flex "blink" frame 24
		flex "eye_happyL" frame 25
		flex "eye_happyR" frame 26
		flex "eye_happy" frame 27
		flex "eye_closeL" frame 28
		flex "eye_closeR" frame 29
		flex "eye_cute" frame 30
		flex "eye_cuteL" frame 31
		flex "eye_cuteR" frame 32
		flex "eye_down" frame 33
		flex "eye_downL" frame 34
		flex "eye_downR" frame 35
		flex "eye_sharp" frame 36
		flex "eye_sharpL" frame 37
		flex "eye_sharpR" frame 38
		flex "eye_bigger" frame 39
		flex "eye_nagomi" frame 40
		flex "eye_taunt" frame 41
		flex "eye_tear" frame 42
		flex "eye_ball" frame 43
		flex "eye_ball2" frame 44
		flex "eye_scared" frame 45
		flex "eye_star" frame 46
		flex "eye_love" frame 47
		flex "eye_reflective" frame 48
		flex "eye_collapse" frame 49
		flex "brow_happy" frame 50
		flex "brow_serious" frame 51
		flex "brow_angry" frame 52
		flex "brow_sad" frame 53
		flex "brow_sleepy" frame 54
		flex "brow_down" frame 55
		flex "brow_up" frame 56
		flex "brow_front" frame 57
		flex "breast_cleavage" frame 58
		flex "breast_smaller" frame 59
		flex "breast_bigger" frame 60
		flex "face_red" frame 61
		flex "face_red2" frame 62
	}

	flexcontroller mouth_a range 0 1 "mouth_a"
	flexcontroller mouth_i range 0 1 "mouth_i"
	flexcontroller mouth_u range 0 1 "mouth_u"
	flexcontroller mouth_e range 0 1 "mouth_e"
	flexcontroller mouth_o range 0 1 "mouth_o"
	flexcontroller mouth_wa range 0 1 "mouth_wa"
	flexcontroller mouth_unhappy range 0 1 "mouth_unhappy"
	flexcontroller mouth_triangle range 0 1 "mouth_triangle"
	flexcontroller mouth_triangle2 range 0 1 "mouth_triangle2"
	flexcontroller mouth_meow range 0 1 "mouth_meow"
	flexcontroller mouth_meow2 range 0 1 "mouth_meow2"
	flexcontroller mouth_smile range 0 1 "mouth_smile"
	flexcontroller mouth_wow range 0 1 "mouth_wow"
	flexcontroller mouth_tongue range 0 1 "mouth_tongue"
	flexcontroller mouth_tongue2 range 0 1 "mouth_tongue2"
	flexcontroller mouth_gasp range 0 1 "mouth_gasp"
	flexcontroller mouth_grin range 0 1 "mouth_grin"
	flexcontroller mouth_ehh range 0 1 "mouth_ehh"
	flexcontroller face_bigger range 0 1 "face_bigger"
	flexcontroller mouth_up range 0 1 "mouth_up"
	flexcontroller mouth_down range 0 1 "mouth_down"
	flexcontroller tongue_thin range 0 1 "tongue_thin"
	flexcontroller tongue_thick range 0 1 "tongue_thick"
	flexcontroller eyelid range 0 1 "blink"
	flexcontroller eye_happyL range 0 1 "eye_happyL"
	flexcontroller eye_happyR range 0 1 "eye_happyR"
	flexcontroller eye_happy range 0 1 "eye_happy"
	flexcontroller eye_closeL range 0 1 "eye_closeL"
	flexcontroller eye_closeR range 0 1 "eye_closeR"
	flexcontroller eye_cute range 0 1 "eye_cute"
	flexcontroller eye_cuteL range 0 1 "eye_cuteL"
	flexcontroller eye_cuteR range 0 1 "eye_cuteR"
	flexcontroller eye_down range 0 1 "eye_down"
	flexcontroller eye_downL range 0 1 "eye_downL"
	flexcontroller eye_downR range 0 1 "eye_downR"
	flexcontroller eye_sharp range 0 1 "eye_sharp"
	flexcontroller eye_sharpL range 0 1 "eye_sharpL"
	flexcontroller eye_sharpR range 0 1 "eye_sharpR"
	flexcontroller eye_bigger range 0 1 "eye_bigger"
	flexcontroller eye_nagomi range 0 1 "eye_nagomi"
	flexcontroller eye_taunt range 0 1 "eye_taunt"
	flexcontroller eye_tear range 0 1 "eye_tear"
	flexcontroller eye_ball range 0 1 "eye_ball"
	flexcontroller eye_ball2 range 0 1 "eye_ball2"
	flexcontroller eye_scared range 0 1 "eye_scared"
	flexcontroller eye_star range 0 1 "eye_star"
	flexcontroller eye_love range 0 1 "eye_love"
	flexcontroller eye_reflective range 0 1 "eye_reflective"
	flexcontroller eye_collapse range 0 1 "eye_collapse"
	flexcontroller brow_happy range 0 1 "brow_happy"
	flexcontroller brow_serious range 0 1 "brow_serious"
	flexcontroller brow_angry range 0 1 "brow_angry"
	flexcontroller brow_sad range 0 1 "brow_sad"
	flexcontroller brow_sleepy range 0 1 "brow_sleepy"
	flexcontroller brow_down range 0 1 "brow_down"
	flexcontroller brow_up range 0 1 "brow_up"
	flexcontroller brow_front range 0 1 "brow_front"
	flexcontroller breast_cleavage range 0 1 "breast_cleavage"
	flexcontroller breast_smaller range 0 1 "breast_smaller"
	flexcontroller breast_bigger range 0 1 "breast_bigger"
	flexcontroller face_red range 0 1 "face_red"
	flexcontroller face_red2 range 0 1 "face_red2"
	flexcontroller face_shadow range 0 1 "face_shadow"

	localvar face_shadow
	%mouth_a = mouth_a
	%mouth_i = mouth_i
	%mouth_u = mouth_u
	%mouth_e = mouth_e
	%mouth_o = mouth_o
	%mouth_wa = mouth_wa
	%mouth_unhappy = mouth_unhappy
	%mouth_triangle = mouth_triangle
	%mouth_triangle2 = mouth_triangle2
	%mouth_meow = mouth_meow
	%mouth_meow2 = mouth_meow2
	%mouth_smile = mouth_smile
	%mouth_wow = mouth_wow
	%mouth_tongue = mouth_tongue
	%mouth_tongue2 = mouth_tongue2
	%mouth_gasp = mouth_gasp
	%mouth_grin = mouth_grin
	%mouth_ehh = mouth_ehh
	%face_bigger = face_bigger
	%mouth_up = mouth_up
	%mouth_down = mouth_down
	%tongue_thin = tongue_thin
	%tongue_thick = tongue_thick
	%blink = blink
	%eye_happyL = eye_happyL
	%eye_happyR = eye_happyR
	%eye_happy = eye_happy
	%eye_closeL = eye_closeL
	%eye_closeR = eye_closeR
	%eye_cute = eye_cute
	%eye_cuteL = eye_cuteL
	%eye_cuteR = eye_cuteR
	%eye_down = eye_down
	%eye_downL = eye_downL
	%eye_downR = eye_downR
	%eye_sharp = eye_sharp
	%eye_sharpL = eye_sharpL
	%eye_sharpR = eye_sharpR
	%eye_bigger = eye_bigger
	%eye_nagomi = eye_nagomi
	%eye_taunt = eye_taunt
	%eye_tear = eye_tear
	%eye_ball = eye_ball
	%eye_ball2 = eye_ball2
	%eye_scared = eye_scared
	%eye_star = eye_star
	%eye_love = eye_love
	%eye_reflective = eye_reflective
	%eye_collapse = eye_collapse
	%brow_happy = brow_happy
	%brow_serious = brow_serious
	%brow_angry = brow_angry
	%brow_sad = brow_sad
	%brow_sleepy = brow_sleepy
	%brow_down = brow_down
	%brow_up = brow_up
	%brow_front = brow_front
	%breast_cleavage = breast_cleavage
	%breast_smaller = breast_smaller
	%breast_bigger = breast_bigger
	%face_red = face_red
	%face_red2 = face_red2
	%face_shadow = face_shadow
} */
$bodygroup "Sanae Body"
{
	studio "Sanae_body.smd"
}
$bodygroup "Hair"
{
	studio "Sanae_hair.smd"
}
/* $bodygroup "Accessory"
{
	studio "Sanae_accessory.smd"
	studio "Sanae_frog.smd"
	studio "Sanae_snake.smd"
	blank
} */
$bodygroup "Skirt"
{
	studio "Sanae_skirt.smd"
}
$bodygroup "Sleeve"
{
	studio "Sanae_sleeve.smd"
	blank
}


$surfaceprop "flesh"

$contents "solid"

$illumposition -0.014 1.663 36.346

$ambientboost

$mostlyopaque

$cdmaterials "models\Sanae\"

$attachment "eyes" "ValveBiped.Bip01_Head1" 2.04 -3.5 0 rotate 0 -80.1 -90
$attachment "mouth" "ValveBiped.Bip01_Head1" -0.3 -3.5 0 rotate 0 -80 -90
$attachment "chest" "ValveBiped.Bip01_Spine2" 5 4 0 rotate 0 90 90
$attachment "forward" "ValveBiped.Bip01_Head1" 0 0 0 rotate 0 -76 -90
$attachment "anim_attachment_RH" "ValveBiped.Bip01_R_Hand" 2.43 -1.55 -0.19 rotate 4.36 0.17 -179.99
$attachment "anim_attachment_LH" "ValveBiped.Bip01_L_Hand" 2.43 -1.55 0.19 rotate 4.36 -179.83 0.01
$attachment "anim_attachment_head" "ValveBiped.Bip01_Head1" 0 0 0 rotate -90 -90 0

$cbox 0 0 0 0 0 0

$bbox -13 -13 0 13 13 72

$hboxset "default"
$hbox 3 "ValveBiped.Bip01_Pelvis" -6 -4.5 -4.5 6 4.5 4.5
$hbox 6 "ValveBiped.Bip01_L_Thigh" -1 -3.4 -2.85 17 2.6 2.15
$hbox 6 "ValveBiped.Bip01_L_Calf" 0.5 -1.5 -2 15.5 2.5 2
$hbox 7 "ValveBiped.Bip01_R_Thigh" -1 -3.4 -2.25 17 2.6 2.75
$hbox 7 "ValveBiped.Bip01_R_Calf" 0.5 -1.5 -2 15.5 2.5 2
$hbox 3 "ValveBiped.Bip01_Spine1" -3.5 -2 -5 1.5 6 5
$hbox 2 "ValveBiped.Bip01_Spine2" -3 -2.25 -4.5 10 6.25 4.5
$hbox 1 "ValveBiped.Bip01_Head1" -1 -4.5 -4.3 9 4.5 3.7
$hbox 4 "ValveBiped.Bip01_L_UpperArm" -2 -1.9 -1.8 9 1.7 1.8
$hbox 4 "ValveBiped.Bip01_L_Forearm" -0.5 -1.5 -1.5 10.5 1.5 1.5
$hbox 4 "ValveBiped.Bip01_L_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$hbox 5 "ValveBiped.Bip01_R_UpperArm" -2 -1.9 -1.8 9 1.7 1.8
$hbox 5 "ValveBiped.Bip01_R_Forearm" -0.5 -1.5 -1.5 10.5 1.5 1.5
$hbox 5 "ValveBiped.Bip01_R_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$hbox 7 "ValveBiped.Bip01_R_Foot" -1.5 -1.5 -1.75 5.5 1.5 1.75
$hbox 6 "ValveBiped.Bip01_L_Foot" -1.5 -1.5 -1.75 5.5 1.5 1.75
$hbox 0 "ValveBiped.Bip01_L_Toe0" -0.5 -1.5 -1.5 2.5 1.5 1.5
$hbox 0 "ValveBiped.Bip01_R_Toe0" -0.5 -1.5 -1.5 2.5 1.5 1.5
$skipboneinbbox

$definebone "ValveBiped.Bip01_Pelvis" "" -0.012192 -0.737503 37.904503 0 0 89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine" "ValveBiped.Bip01_Pelvis" 0.000004 1.780952 -1.572807 -0.602866 90.000897 89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine1" "ValveBiped.Bip01_Spine" 3.571568 0.000007 0.000055 -0.001031 -6.451906 0.000115 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine2" "ValveBiped.Bip01_Spine1" 3.367271 -0.000014 -0.00001 0.000172 -0.724447 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 7.619949 0.069456 -0.000002 0.000115 8.92737 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Neck1" "ValveBiped.Bip01_Spine4" 2.352249 0.024923 0.000004 -0.000229 13.009353 179.999841 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Head1" "ValveBiped.Bip01_Neck1" 3.211861 0.00001 0.000008 0.000229 6.359772 0 0 0 0 0 0 0
$definebone "ValveBiped.forward" "ValveBiped.Bip01_Head1" -0.000004 -0.000001 0 -0.000057 -75.838077 -89.999641 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Eye" "ValveBiped.Bip01_Head1" 2.942585 -0.168736 1.373597 -89.038155 9.997771 90.005713 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Eye" "ValveBiped.Bip01_Head1" 2.951077 -0.167235 -1.326224 -86.39509 -169.996633 -90.000132 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 1.883522 0.844616 1.900872 -76.440226 166.165361 93.870459 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 2.974381 0.045948 0.084272 5.331363 -27.567907 -82.408807 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 9.383965 0 -0.000008 -2.6268 -2.27479 0.169812 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Ulna" "ValveBiped.Bip01_L_Forearm" 4.197487 0.000034 0.000004 -0.000056 0.000286 -1.769637 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 8.394958 0.000068 -0.000004 -0.00006 0.000401 -3.297828 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 8.394959 0.000067 0.000011 -2.211449 2.080009 86.253412 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 3.192091 0.174259 -0.464076 -2.573553 -14.783521 3.947394 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.256596 -0.053257 -0.077846 3.305507 7.195545 2.441658 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 0.732945 0.000004 -0.000005 -5.693881 -11.671496 14.314888 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.245901 0.086472 0.146991 -2.998517 -9.824045 8.155193 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 1.4728 -0.052143 -0.073872 2.246796 3.074888 -2.069472 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 0.814636 0.000015 -0.000006 -0.325211 -5.672065 -0.07151 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.257687 -0.043201 0.699123 -8.549331 -5.874361 17.353687 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.150517 -0.055359 -0.05784 4.855644 -8.638194 -1.190851 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 0.889768 0.02404 -0.032714 1.158576 4.255768 1.317561 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 2.976648 -0.125774 -1.194675 -6.879389 -6.083316 12.274133 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 0.899957 -0.04612 -0.020476 4.456578 -4.93707 -23.448658 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.519157 0 -0.000004 -0.735274 -3.248736 11.126112 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.082935 -0.343479 0.642813 -47.328365 -30.245365 -4.283488 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.06354 0.000004 -0.000015 2.505843 5.982934 -9.684407 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 0.839828 0.000006 -0.000006 6.207672 -0.850045 -18.319054 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Trapezius" "ValveBiped.Bip01_L_Clavicle" 2.31173 0.045975 0.084272 -0.000115 0.000115 -0.000056 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 1.883533 0.844621 -1.927183 76.440287 166.163189 -97.983271 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 2.849924 0.005619 -0.083995 -3.263338 -24.714993 85.874124 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 9.511887 -0.00806 0.434433 -0.496467 -2.39101 -0.040337 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 8.464421 0.000078 0.000027 2.240205 1.710164 -86.05843 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.090565 0.038231 -0.071615 1.209056 -6.830576 -5.343634 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 1.30106 0.012943 -0.047763 0.107028 -16.74962 4.843786 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 0.976044 0.040375 0.058751 -0.476931 14.464992 -0.449542 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.099703 -0.100552 -0.632339 7.310941 -6.793962 -17.159856 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.307212 -0.017288 0.064595 -3.724223 -8.902051 0.073051 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 0.765945 -0.000015 -0.000008 -5.769457 6.446111 2.36477 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 3.038944 0.13422 0.694636 4.60005 -10.262311 -10.04206 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.184647 -0.001595 -0.000536 -2.620937 -4.270081 -0.253587 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 0.762941 -0.000008 0.000003 0.942573 -1.034358 -4.677278 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 2.920496 0.008446 1.209888 -1.985528 -14.25594 -8.301185 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 0.746387 -0.020584 0.022526 7.71001 3.155504 -15.763153 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.61174 0.006821 -0.017462 -7.518751 -3.919151 -0.324626 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.079817 -0.412884 -0.682626 43.527833 -28.82947 103.379066 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.082533 0.000015 0.000002 3.174184 5.135081 13.008954 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 0.85482 0.000008 -0.000013 4.231069 -10.231249 1.169357 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 8.464421 0.000078 0.000027 -0.000003 0.000286 3.734424 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Ulna" "ValveBiped.Bip01_R_Forearm" 4.232212 0.00004 0.000031 -0.000061 0.000688 2.001514 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Trapezius" "ValveBiped.Bip01_R_Clavicle" 2.18728 0.005619 -0.083997 -0.000172 0.000343 0.000114 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Thigh" "ValveBiped.Bip01_Pelvis" 3.708055 -0.000004 -0.000003 1.780638 -92.308197 -89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Calf" "ValveBiped.Bip01_L_Thigh" 15.395992 -0.008405 0.01101 -0.991561 2.959957 -0.000057 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Foot" "ValveBiped.Bip01_L_Calf" 18.806452 -0.102108 0.046136 -4.40255 -70.478051 0.515032 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Toe0" "ValveBiped.Bip01_L_Foot" 5.886008 -0.000038 -0.000001 0.053455 -28.677611 -0.638676 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Ankle" "ValveBiped.Bip01_L_Calf" 17.653545 -0.154161 0.043002 0 0.000516 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Thigh" "ValveBiped.Bip01_Pelvis" -3.708055 0.000008 0.000006 1.781956 -87.560498 -90.02748 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Calf" "ValveBiped.Bip01_R_Thigh" 15.395952 -0.0085 -0.011642 1.02697 2.959384 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Foot" "ValveBiped.Bip01_R_Calf" 18.806318 -0.102044 -0.049196 2.767385 -70.654291 -0.761346 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Toe0" "ValveBiped.Bip01_R_Foot" 5.886011 -0.00003 0.000001 -0.35449 -28.588192 -4.50637 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Ankle" "ValveBiped.Bip01_R_Calf" 17.653444 -0.154087 -0.046152 0 0.001032 0 0 0 0 0 0 0
$definebone "j_hair_r_01" "ValveBiped.Bip01_Head1" 4.421242 -1.909435 3.664769 6.434703 -175.87259 179.999937 0 0 0 0 0 0
$definebone "j_hair_r_02" "j_hair_r_01" 4.68399 -0.000006 -0.000004 1.608122 -46.952636 -7.720896 0 0 0 0 0 0
$definebone "j_hair_r_03" "j_hair_r_02" 5.457756 0 0.000001 0.000002 9.560772 0 0 0 0 0 0 0
$definebone "j_hair_l_01" "ValveBiped.Bip01_Head1" 4.655739 -2.001987 -3.435415 -5.349478 -175.282871 -0.000229 0 0 0 0 0 0
$definebone "j_hair_l_02" "j_hair_l_01" 5.094971 0.00001 -0.000001 7.54803 72.177327 0.912493 0 0 0 0 0 0
$definebone "j_hair_l_03" "j_hair_l_02" 5.192093 0.000008 0.000001 10.698203 -33.080174 -13.257156 0 0 0 0 0 0
$definebone "j_hair_l_04" "j_hair_l_03" 5.436024 -0.000023 0 -0.000006 -19.803997 0.000005 0 0 0 0 0 0
$definebone "j_hair_l_05" "j_hair_l_04" 4.731808 0.000048 0.000012 0.000224 1.388057 0.000009 0 0 0 0 0 0
$definebone "j_hair_f_01" "ValveBiped.Bip01_Head1" 7.119461 -3.152153 0.000008 0.000172 -164.625277 -0.000115 0 0 0 0 0 0
$definebone "j_hair_f_02" "j_hair_f_01" 2.814533 -0.000011 0.000001 0 -17.17017 0 0 0 0 0 0 0
$definebone "j_hair_b_01" "ValveBiped.Bip01_Head1" 1.994446 4.870107 0.000036 -0.000057 154.904073 -0.000172 0 0 0 0 0 0
$definebone "j_hair_b_02" "j_hair_b_01" 5.89941 -0.000004 0 0 9.927524 0 0 0 0 0 0 0
$definebone "j_hair_b_03" "j_hair_b_02" 5.630047 0.000002 0 0 5.42293 0 0 0 0 0 0 0
$definebone "j_hair_b_04" "j_hair_b_03" 6.220745 -0.000006 0 0 -3.671628 0 0 0 0 0 0 0
$definebone "j_hair_bl_01" "j_hair_b_01" 8.76215 1.396511 -4.498487 10.03421 8.195529 -5.052283 0 0 0 0 0 0
$definebone "j_hair_bl_02" "j_hair_bl_01" 7.805508 -0.000038 0.000002 0 17.132638 0.000001 0 0 0 0 0 0
$definebone "j_hair_br_01" "j_hair_b_01" 8.773476 1.39959 4.506257 -7.704676 8.6009 3.824206 0 0 0 0 0 0
$definebone "j_hair_br_02" "j_hair_br_01" 7.649887 -0.00004 0 0.000056 15.94266 -0.000228 0 0 0 0 0 0
$definebone "j_hair_br_03" "j_hair_b_01" 7.63496 2.571785 8.971973 -10.350712 9.908674 4.614487 0 0 0 0 0 0
$definebone "j_hair_br_04" "j_hair_br_03" 9.289852 0.000006 0.000002 0 -0.000003 -0.000001 0 0 0 0 0 0
$definebone "j_hair_bl_03" "j_hair_b_01" 7.4305 2.69326 -9.271919 11.131139 8.487342 -5.287427 0 0 0 0 0 0
$definebone "j_hair_bl_04" "j_hair_bl_03" 8.829102 0.000004 0 -0.000001 0.000003 0.000001 0 0 0 0 0 0
$definebone "p_skirt_e_helper" "ValveBiped.Bip01_L_Thigh" 2.092991 0.672164 3.294092 -7.684394 -1.78018 -90.000153 0 0 0 0 0 0
$definebone "p_skirt_e_01" "p_skirt_e_helper" 6.501236 -0.000061 -0.000051 0.000687 -7.152803 -0.000057 0 0 0 0 0 0
$definebone "p_skirt_e_02" "p_skirt_e_01" 4.91431 0.000014 0.000019 -0.000344 -2.031015 0 0 0 0 0 0 0
$definebone "p_skirt_se_helper" "ValveBiped.Bip01_L_Thigh" 1.680313 -3.272567 1.085591 -11.66078 -2.429112 -179.868647 0 0 0 0 0 0
$definebone "p_skirt_se_01" "p_skirt_se_helper" 6.521082 0.000082 -0.001008 0.018678 2.727107 0.000344 0 0 0 0 0 0
$definebone "p_skirt_se_02" "p_skirt_se_01" 5.665319 -0.000062 0.000978 -0.000458 5.779599 -0.001032 0 0 0 0 0 0
$definebone "p_skirt_w_helper" "ValveBiped.Bip01_R_Thigh" 2.401436 0.663985 -3.033963 9.150308 -1.777602 -89.972135 0 0 0 0 0 0
$definebone "p_skirt_w_01" "p_skirt_w_helper" 6.517076 0.000026 0.000003 0.000057 7.539495 0.000057 0 0 0 0 0 0
$definebone "p_skirt_w_02" "p_skirt_w_01" 4.949772 0.000008 0.000008 -0.000115 2.04477 0 0 0 0 0 0 0
$definebone "p_skirt_sw_helper" "ValveBiped.Bip01_R_Thigh" 1.496826 -2.982049 -1.200154 12.017387 -4.945772 -179.689655 0 0 0 0 0 0
$definebone "p_skirt_sw_01" "p_skirt_sw_helper" 6.295319 0.000034 -0.002542 0.012492 0.07907 -0.000344 0 0 0 0 0 0
$definebone "p_skirt_sw_02" "p_skirt_sw_01" 6.067181 -0.000014 -0.001135 0.011119 5.740298 0.001089 0 0 0 0 0 0
$definebone "p_skirt_n_helper" "ValveBiped.Bip01_Pelvis" 0.000846 -1.981617 -5.161445 1.450099 -89.997865 90.000098 0 0 0 0 0 0
$definebone "p_skirt_n_01" "p_skirt_n_helper" 6.021763 -0.000009 0.000225 -0.00212 -5.338649 0.000229 0 0 0 0 0 0
$definebone "p_skirt_n_02" "p_skirt_n_01" 6.446043 -0.000024 0.000004 0 -2.008504 0 0 0 0 0 0 0
$definebone "p_skirt_nw_helper" "ValveBiped.Bip01_Pelvis" -4.396205 -2.128181 -4.230237 -1.823839 -95.853434 89.89393 0 0 0 0 0 0
$definebone "p_skirt_nw_01" "p_skirt_nw_helper" 5.928001 0 -0.00034 0.001203 -5.724595 -0.000229 0 0 0 0 0 0
$definebone "p_skirt_nw_02" "p_skirt_nw_01" 6.402657 0.00001 -0.000234 0.001948 -0.487187 -0.000057 0 0 0 0 0 0
$definebone "p_skirt_ne_helper" "ValveBiped.Bip01_Pelvis" 3.809694 -2.289825 -4.372347 0.616159 -81.608671 90.642839 0 0 0 0 0 0
$definebone "p_skirt_ne_01" "p_skirt_ne_helper" 5.62035 0.000001 -0.0023 0.025094 -1.66301 -0.000688 0 0 0 0 0 0
$definebone "p_skirt_ne_02" "p_skirt_ne_01" 6.122751 0.000008 0.000181 0.006359 0.080787 0.000057 0 0 0 0 0 0
$definebone "p_sleeve_l_01" "ValveBiped.Bip01_L_Forearm" 2.997192 -0.699812 -1.344616 63.09532 -1.957397 84.649014 0 0 0 0 0 0
$definebone "p_sleeve_l_02" "p_sleeve_l_01" 4.303497 -0.000018 0.000016 -0.000172 2.235445 0.000002 0 0 0 0 0 0
$definebone "p_sleeve_l_03" "p_sleeve_l_02" 4.050243 0 0.000002 0.000229 -2.64736 0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Elbow" "ValveBiped.Bip01_L_UpperArm" 9.383972 0 -0.000008 -3.11298 -5.66732 0.313344 0 0 0 0 0 0
$definebone "p_sleeve_r_01" "ValveBiped.Bip01_R_Forearm" 2.772808 -0.707625 1.379482 -63.324787 -1.948687 95.391631 0 0 0 0 0 0
$definebone "p_sleeve_r_02" "p_sleeve_r_01" 4.426395 0.000004 -0.000006 0.000344 -4.04095 0 0 0 0 0 0 0
$definebone "p_sleeve_r_03" "p_sleeve_r_02" 4.084991 -0.000033 0.00002 -0.000057 0.141012 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Elbow" "ValveBiped.Bip01_R_UpperArm" 9.511887 -0.00806 0.434433 0.000058 -5.732729 -0.000517 0 0 0 0 0 0

$bonemerge "ValveBiped.Bip01_Pelvis"
$bonemerge "ValveBiped.Bip01_Spine"
$bonemerge "ValveBiped.Bip01_Spine1"
$bonemerge "ValveBiped.Bip01_Spine2"
$bonemerge "ValveBiped.Bip01_Spine4"
$bonemerge "ValveBiped.Bip01_R_Clavicle"
$bonemerge "ValveBiped.Bip01_R_UpperArm"
$bonemerge "ValveBiped.Bip01_R_Forearm"
$bonemerge "ValveBiped.Bip01_R_Hand"

$jigglebone "j_hair_r_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_r_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_r_03"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_03"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_04"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_05"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_f_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_f_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_b_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_03"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_04"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_03"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_04"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_03"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_04"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "p_skirt_e_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_e_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_se_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_w_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_w_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_sw_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_sw_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_n_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_n_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_nw_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_nw_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_ne_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_ne_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_l_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_l_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_l_03"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_r_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_r_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_sleeve_r_03"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}

$ikchain "rhand" "ValveBiped.Bip01_R_Hand" knee 0.707 0.707 0
$ikchain "lhand" "ValveBiped.Bip01_L_Hand" knee 0.707 0.707 0
$ikchain "rfoot" "ValveBiped.Bip01_R_Foot" knee 0.707 -0.707 0
$ikchain "lfoot" "ValveBiped.Bip01_L_Foot" knee 0.707 -0.707 0

$ikautoplaylock "rhand" 0 0
$ikautoplaylock "lhand" 0 0
$ikautoplaylock "rfoot" 0.8 0.1
$ikautoplaylock "lfoot" 0.8 0.1

$weightlist "weights_common_male_aim_matrix_run" {
	 "ValveBiped.Bip01_Pelvis" 0
	 "ValveBiped.Bip01_Spine" 0
	 "ValveBiped.Bip01_Spine1" 0
	 "ValveBiped.Bip01_Spine2" 0
	 "ValveBiped.Bip01_Spine4" 0
	 "ValveBiped.Bip01_Neck1" 0
	 "ValveBiped.Bip01_Head1" 0
	 "ValveBiped.forward" 0
	 "ValveBiped.Bip01_R_Eye" 0
	 "ValveBiped.Bip01_L_Eye" 0
	 "ValveBiped.Bip01_L_Clavicle" 0
	 "ValveBiped.Bip01_L_UpperArm" 0
	 "ValveBiped.Bip01_L_Forearm" 0
	 "ValveBiped.Bip01_L_Ulna" 0
	 "ValveBiped.Bip01_L_Wrist" 0
	 "ValveBiped.Bip01_L_Hand" 0
	 "ValveBiped.Bip01_L_Finger3" 0
	 "ValveBiped.Bip01_L_Finger31" 0
	 "ValveBiped.Bip01_L_Finger32" 0
	 "ValveBiped.Bip01_L_Finger2" 0
	 "ValveBiped.Bip01_L_Finger21" 0
	 "ValveBiped.Bip01_L_Finger22" 0
	 "ValveBiped.Bip01_L_Finger1" 0
	 "ValveBiped.Bip01_L_Finger11" 0
	 "ValveBiped.Bip01_L_Finger12" 0
	 "ValveBiped.Bip01_L_Finger4" 0
	 "ValveBiped.Bip01_L_Finger41" 0
	 "ValveBiped.Bip01_L_Finger42" 0
	 "ValveBiped.Bip01_L_Finger0" 0
	 "ValveBiped.Bip01_L_Finger01" 0
	 "ValveBiped.Bip01_L_Finger02" 0
	 "ValveBiped.Bip01_L_Trapezius" 0
	 "ValveBiped.Bip01_R_Clavicle" 0
	 "ValveBiped.Bip01_R_UpperArm" 0
	 "ValveBiped.Bip01_R_Forearm" 0
	 "ValveBiped.Bip01_R_Hand" 0
	 "ValveBiped.Bip01_R_Finger2" 0
	 "ValveBiped.Bip01_R_Finger21" 0
	 "ValveBiped.Bip01_R_Finger22" 0
	 "ValveBiped.Bip01_R_Finger1" 0
	 "ValveBiped.Bip01_R_Finger11" 0
	 "ValveBiped.Bip01_R_Finger12" 0
	 "ValveBiped.Bip01_R_Finger3" 0
	 "ValveBiped.Bip01_R_Finger31" 0
	 "ValveBiped.Bip01_R_Finger32" 0
	 "ValveBiped.Bip01_R_Finger4" 0
	 "ValveBiped.Bip01_R_Finger41" 0
	 "ValveBiped.Bip01_R_Finger42" 0
	 "ValveBiped.Bip01_R_Finger0" 0
	 "ValveBiped.Bip01_R_Finger01" 0
	 "ValveBiped.Bip01_R_Finger02" 0
	 "ValveBiped.Bip01_R_Wrist" 0
	 "ValveBiped.Bip01_R_Ulna" 0
	 "ValveBiped.Bip01_R_Trapezius" 0
	 "ValveBiped.Bip01_L_Thigh" 0
	 "ValveBiped.Bip01_L_Calf" 0
	 "ValveBiped.Bip01_L_Foot" 0
	 "ValveBiped.Bip01_L_Toe0" 0
	 "ValveBiped.Bip01_L_Ankle" 0
	 "ValveBiped.Bip01_R_Thigh" 0
	 "ValveBiped.Bip01_R_Calf" 0
	 "ValveBiped.Bip01_R_Foot" 0
	 "ValveBiped.Bip01_R_Toe0" 0
	 "ValveBiped.Bip01_R_Ankle" 0
	 "j_hair_r_01" 0
	 "j_hair_r_02" 0
	 "j_hair_r_03" 0
	 "j_hair_l_01" 0
	 "j_hair_l_02" 0
	 "j_hair_l_03" 0
	 "j_hair_l_04" 0
	 "j_hair_l_05" 0
	 "j_hair_f_01" 0
	 "j_hair_f_02" 0
	 "j_hair_b_01" 0
	 "j_hair_b_02" 0
	 "j_hair_b_03" 0
	 "j_hair_b_04" 0
	 "j_hair_bl_01" 0
	 "j_hair_bl_02" 0
	 "j_hair_br_01" 0
	 "j_hair_br_02" 0
	 "j_hair_br_03" 0
	 "j_hair_br_04" 0
	 "j_hair_bl_03" 0
	 "j_hair_bl_04" 0
	 "p_skirt_e_helper" 0
	 "p_skirt_e_01" 0
	 "p_skirt_e_02" 0
	 "p_skirt_se_helper" 0
	 "p_skirt_se_01" 0
	 "p_skirt_se_02" 0
	 "p_skirt_w_helper" 0
	 "p_skirt_w_01" 0
	 "p_skirt_w_02" 0
	 "p_skirt_sw_helper" 0
	 "p_skirt_sw_01" 0
	 "p_skirt_sw_02" 0
	 "p_skirt_n_helper" 0
	 "p_skirt_n_01" 0
	 "p_skirt_n_02" 0
	 "p_skirt_nw_helper" 0
	 "p_skirt_nw_01" 0
	 "p_skirt_nw_02" 0
	 "p_skirt_ne_helper" 0
	 "p_skirt_ne_01" 0
	 "p_skirt_ne_02" 0
	 "p_sleeve_l_01" 0
	 "p_sleeve_l_02" 0
	 "p_sleeve_l_03" 0
	 "ValveBiped.Bip01_L_Elbow" 0
	 "p_sleeve_r_01" 0
	 "p_sleeve_r_02" 0
	 "p_sleeve_r_03" 0
	 "ValveBiped.Bip01_R_Elbow" 0
}

// $animation "a_proportions_corrective_animation" "common_female_tanktop_jeans_rain_anims\a_proportions_corrective_animation.smd" {
// }

/* $animation "a_proportions_corrective_animation" "common_female_tanktop_jeans_rain_anims\a_proportions_corrective_animation.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$animation "a_proportions" "common_female_tanktop_jeans_rain_anims\a_proportions.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_proportions_corrective_animation" 0
} */

$sequence "ragdoll" {
	"common_female_tanktop_jeans_rain_anims\ragdoll.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_01" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_01.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_02" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_02.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_03" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_03.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_04" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_04.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_05" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_05.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "ragdoll_06" {
	"common_female_tanktop_jeans_rain_anims\ragdoll_06.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

// $declaresequence "common_male_aim_matrix_run"

// $declaresequence "common_male_aimmatrix_Standing_Alert"

// $declaresequence "common_male_AimMatrix_Standing"

// $declaresequence "common_male_aimmatrix_Standing_Acquiring"

// $declaresequence "Idlenoise"

// $declaresequence "Idle"

// $declaresequence "Idle_Alert_01a"

// $declaresequence "Idle_Alert_01b"

// $declaresequence "Idle_Alert_01c"

// $declaresequence "Idle_Alert_02a"

// $declaresequence "Idle_Alert_02b"

// $declaresequence "Idle_Alert_02c"

// $declaresequence "Idle_Alert_03"

// $declaresequence "Idle_Alert_Behind_02"

// $declaresequence "Idle_Alert_Behind_03"

// $declaresequence "Idle_Alert_Left_04"

// $declaresequence "Idle_Alert_Left_01"

// $declaresequence "Idle_Alert_Right_02a"

// $declaresequence "Idle_Alert_Right_02d"

// $declaresequence "Idle_Alert_Straight_05"

// $declaresequence "Idle_Alert_Straight_08"

// $declaresequence "violent_alert01_Common_a"

// $declaresequence "violent_alert01_Common_D"

// $declaresequence "violent_alert01_Common_E"

// $declaresequence "violent_alert01_Common_B"

// $declaresequence "violent_alert01_Common_C"

// $declaresequence "Idle_Alert_Injured_Behind_01"

// $declaresequence "Idle_Alert_Injured_Left_02"

// $declaresequence "Idle_Alert_Injured_Right_02"

// $declaresequence "Idle_Alert_Injured_Straight_02"

// $declaresequence "Idle_Acquire_05"

// $declaresequence "Idle_Acquire_06"

// $declaresequence "Idle_Acquire_11"

// $declaresequence "Idle_UnableToReachTarget_01a"

// $declaresequence "Idle_UnableToReachTarget_01b"

// $declaresequence "Idle_UnableToReachTarget_01c"

// $declaresequence "Idle_UnableToReachTarget_01d"

// $declaresequence "Idle_Neutral_01"

// $declaresequence "Idle_Neutral_02"

// $declaresequence "Idle_Neutral_03"

// $declaresequence "Idle_Neutral_06"

// $declaresequence "Idle_Neutral_07"

// $declaresequence "Idle_Neutral_08"

// $declaresequence "Idle_Neutral_10"

// $declaresequence "Idle_Neutral_11"

// $declaresequence "Idle_Neutral_12"

// $declaresequence "Idle_Neutral_13"

// $declaresequence "Idle_Neutral_14"

// $declaresequence "Idle_Neutral_15"

// $declaresequence "Idle_Neutral_16"

// $declaresequence "Idle_Neutral_17"

// $declaresequence "Idle_Crouching_Neutral_01"

// $declaresequence "Idle_Crouching_Neutral_02"

// $declaresequence "Idle_Neutral_Turn_Right"

// $declaresequence "Idle_Neutral_Turn_Left"

// $declaresequence "Idle_Neutral_Turn_Around_01a"

// $declaresequence "Idle_Neutral_Turn_Around_01b"

// $declaresequence "Idle_Neutral_Turn_Around_01c"

// $declaresequence "Crouch_Idle_Upper_KNIFE"

// $declaresequence "Idle_Neutral_to_Alert_01"

// $declaresequence "Idle_Alert_to_Neutral_01"

// $declaresequence "Running_to_Standing"

// $declaresequence "Running_to_Standing_02"

// $declaresequence "Walk_Neutral_01"

// $declaresequence "Walk_Neutral_02"

// $declaresequence "Walk_Neutral_02b"

// $declaresequence "Walk_Neutral_03"

// $declaresequence "Walk_Neutral_04a"

// $declaresequence "Walk_Neutral_04b"

// $declaresequence "Walk_Neutral_South"

// $declaresequence "Shamble_01"

// $declaresequence "Shamble_02"

// $declaresequence "Shamble_03"

// $declaresequence "Walk"

// $declaresequence "CrouchWalk_01"

// $declaresequence "CrouchWalk_03"

// $declaresequence "MeleeAlign"

// $declaresequence "Run_01"

// $declaresequence "Run_01b"

// $declaresequence "Run_02"

// $declaresequence "Run_02b"

// $declaresequence "Run_03"

// $declaresequence "Run_03b"

// $declaresequence "Run_04"

// $declaresequence "Run_05"

// $declaresequence "Run_OnFire"

// $declaresequence "Run_OnFire_01"

// $declaresequence "Standing_OnFire"

// $declaresequence "Run_Stumble_01"

// $declaresequence "Melee_01"

// $declaresequence "Melee_02"

// $declaresequence "Melee_03"

// $declaresequence "Melee_04"

// $declaresequence "Melee_Moving01_Delta"

// $declaresequence "Melee_Moving01_Layer"

// $declaresequence "Melee_Moving01"

// $declaresequence "Melee_Moving02_Delta"

// $declaresequence "Melee_Moving02_Layer"

// $declaresequence "Melee_Moving02"

// $declaresequence "Melee_Moving03_Delta"

// $declaresequence "Melee_Moving03_Layer"

// $declaresequence "Melee_Moving03"

// $declaresequence "Melee_Moving04_Delta"

// $declaresequence "Melee_Moving04_Layer"

// $declaresequence "Melee_Moving04"

// $declaresequence "Melee_Moving05_Delta"

// $declaresequence "Melee_Moving05_Layer"

// $declaresequence "Melee_Moving05"

// $declaresequence "Melee_Moving06_Delta"

// $declaresequence "Melee_Moving06_Layer"

// $declaresequence "Melee_Moving06"

// $declaresequence "AttackIncap_01"

// $declaresequence "AttackIncap_03"

// $declaresequence "AttackDoor_01"

// $declaresequence "AttackDoor_ReachThrough"

// $declaresequence "Shoved_Backward_01"

// $declaresequence "Shoved_Backward_02"

// $declaresequence "Shoved_Backward_03"

// $declaresequence "Shoved_Backward_03a"

// $declaresequence "Shoved_Backward_04e"

// $declaresequence "Shoved_Backward_04g"

// $declaresequence "Shoved_Backward_04i"

// $declaresequence "Shoved_Backward_04j"

// $declaresequence "Shoved_Backward_04m"

// $declaresequence "Shoved_Backward_04o"

// $declaresequence "Shoved_Forward_01"

// $declaresequence "Shoved_Leftward_01"

// $declaresequence "Shoved_Rightward_01"

// $declaresequence "Shoved_Backward_IntoWall_01"

// $declaresequence "Shoved_Backward_IntoWall_02"

// $declaresequence "Shoved_Backward_IntoWall_03"

// $declaresequence "Shoved_Backward_IntoWall_04"

// $declaresequence "Shoved_Forward_IntoWall_02"

// $declaresequence "Shoved_Leftward_IntoWall_02"

// $declaresequence "Shoved_Rightward_IntoWall_01"

// $declaresequence "Jump_01"

// $declaresequence "Jump_02"

// $declaresequence "Jump_Across_01"

// $declaresequence "Jump_Across_02"

// $declaresequence "Jump_Up_To_Ledge_01"

// $declaresequence "Jump_Up_To_Ledge_04"

// $declaresequence "Jump_Up_To_Ledge_02"

// $declaresequence "Jump_Up_To_Ledge_03_Tall"

// $declaresequence "Jump_Down_From_Ledge_Extraction"

// $declaresequence "Jump_Down_From_Ledge_NoMotion"

// $declaresequence "Jump_Down_From_Ledge_Walkframe"

// $declaresequence "Ledge_Climb"

// $declaresequence "Fall_01"

// $declaresequence "Fall_02"

// $declaresequence "Fall_03"

// $declaresequence "Fall_04"

// $declaresequence "Fall_05"

// $declaresequence "Fall_06"

// $declaresequence "Fall_07"

// $declaresequence "Fall_08"

// $declaresequence "Fall_09"

// $declaresequence "Landing01_Neutral"

// $declaresequence "Landing_Hard01_Neutral"

// $declaresequence "Landing01"

// $declaresequence "Landing02"

// $declaresequence "Landing03"

// $declaresequence "Landing04"

// $declaresequence "Landing_Hard01"

// $declaresequence "Landing_Hard02"

// $declaresequence "Landing_Hard03"

// $declaresequence "Landing_Hard04"

// $declaresequence "Landing_Hard05"

// $declaresequence "Landing_Hard06"

// $declaresequence "Climb24_01_InPlace"

// $declaresequence "Climb24_02_InPlace"

// $declaresequence "Climb24_03_InPlace"

// $declaresequence "Climb36_01_InPlace"

// $declaresequence "Climb36_02_InPlace"

// $declaresequence "Climb36_03_InPlace"

// $declaresequence "Climb36_04_InPlace"

// $declaresequence "Climb48_01_InPlace"

// $declaresequence "Climb48_02_InPlace"

// $declaresequence "Climb48_03_InPlace"

// $declaresequence "Climb48_04_InPlace"

// $declaresequence "Climb60_01_InPlace"

// $declaresequence "Climb60_02_InPlace"

// $declaresequence "Climb60_03_InPlace"

// $declaresequence "Climb60_04_InPlace"

// $declaresequence "Climb72_03_InPlace"

// $declaresequence "Climb72_04_InPlace"

// $declaresequence "Climb72_05_InPlace"

// $declaresequence "Climb72_06_InPlace"

// $declaresequence "Climb72_07_InPlace"

// $declaresequence "Climb84_01_InPlace"

// $declaresequence "Climb84_03_InPlace"

// $declaresequence "Climb84_04_InPlace"

// $declaresequence "Climb84_05_InPlace"

// $declaresequence "Climb84_06_InPlace"

// $declaresequence "Climb96_05_InPlace"

// $declaresequence "Climb96_00_InPlace"

// $declaresequence "Climb96_00a_InPlace"

// $declaresequence "Climb96_03_InPlace"

// $declaresequence "Climb96_03a_InPlace"

// $declaresequence "Climb96_04a_InPlace"

// $declaresequence "Climb108_01_InPlace"

// $declaresequence "Climb108_00_InPlace"

// $declaresequence "Climb108_00a_InPlace"

// $declaresequence "Climb108_03_InPlace"

// $declaresequence "Climb108_03a_InPlace"

// $declaresequence "Climb108_04_InPlace"

// $declaresequence "Climb120_01_InPlace"

// $declaresequence "Climb120_00_InPlace"

// $declaresequence "Climb120_00a_InPlace"

// $declaresequence "Climb120_03_InPlace"

// $declaresequence "Climb120_03a_InPlace"

// $declaresequence "Climb120_04_InPlace"

// $declaresequence "Climb132_01_InPlace"

// $declaresequence "Climb132_00_InPlace"

// $declaresequence "Climb132_00a_InPlace"

// $declaresequence "Climb132_03_InPlace"

// $declaresequence "Climb132_03a_InPlace"

// $declaresequence "Climb132_04_InPlace"

// $declaresequence "Climb144_01_InPlace"

// $declaresequence "Climb144_00_InPlace"

// $declaresequence "Climb144_00a_InPlace"

// $declaresequence "Climb144_03_InPlace"

// $declaresequence "Climb144_03a_InPlace"

// $declaresequence "Climb144_04_InPlace"

// $declaresequence "Climb156_01_InPlace"

// $declaresequence "Climb156_00_InPlace"

// $declaresequence "Climb156_00a_InPlace"

// $declaresequence "Climb156_03_InPlace"

// $declaresequence "Climb156_03a_InPlace"

// $declaresequence "Climb156_04_InPlace"

// $declaresequence "Climb168_01_InPlace"

// $declaresequence "Climb168_00_InPlace"

// $declaresequence "Climb168_00a_InPlace"

// $declaresequence "Climb168_03_InPlace"

// $declaresequence "Climb168_03a_InPlace"

// $declaresequence "Climb168_04_InPlace"

// $declaresequence "Climb36_Hurdle_04_InPlace"

// $declaresequence "Ladder_Ascend"

// $declaresequence "Ladder_Descend"

// $declaresequence "Ladder_Dismount_01"

// $declaresequence "Ladder_Dismount_02"

// $declaresequence "Ladder_Dismount_03"

// $declaresequence "LyingIdlenoise"

// $declaresequence "SittingIdlenoise"

// $declaresequence "Standing_to_Sitting03"

// $declaresequence "Sitting01"

// $declaresequence "Sitting02"

// $declaresequence "Sitting03"

// $declaresequence "Sitting04"

// $declaresequence "Sitting05"

// $declaresequence "Sitting06"

// $declaresequence "Sitting07"

// $declaresequence "Sitting08"

// $declaresequence "Sitting09"

// $declaresequence "Sitting03_to_Standing"

// $declaresequence "Sitting_to_Standing_Alert"

// $declaresequence "Shoved_Backward_Sit_04i"

// $declaresequence "Shoved_Backward_Sit_04o"

// $declaresequence "Shoved_Sitting_Leftward"

// $declaresequence "Shoved_Sitting_Rightward"

// $declaresequence "Standing_to_Sitting_in_Chair"

// $declaresequence "Sitting_in_Chair01"

// $declaresequence "Sitting_in_Chair_to_Standing"

// $declaresequence "Sitting_in_Chair_to_Standing_Alert"

// $declaresequence "Standing_to_Lying03"

// $declaresequence "Lying01"

// $declaresequence "Lying02"

// $declaresequence "Lying03"

// $declaresequence "Lying04"

// $declaresequence "Lying05"

// $declaresequence "Lying06"

// $declaresequence "Lying07"

// $declaresequence "Lying08"

// $declaresequence "Lying03_to_Standing"

// $declaresequence "Lying_to_Standing_Alert"

// $declaresequence "Lying_to_Standing_Alert03c"

// $declaresequence "Lying_to_Standing_Alert03d"

// $declaresequence "Lying03_to_Sitting03"

// $declaresequence "Sitting03_to_Lying03"

// $declaresequence "LeaningIdlenoise"

// $declaresequence "LeaningIdlenoise_RT"

// $declaresequence "LeaningIdlenoise_LT"

// $declaresequence "LeaningIdlenoise_Both"

// $declaresequence "LeaningRightward01"

// $declaresequence "LeaningRightward02"

// $declaresequence "LeaningRightward03"

// $declaresequence "LeaningRightward04"

// $declaresequence "LeaningBackward01"

// $declaresequence "LeaningBackward02"

// $declaresequence "LeaningBackward03"

// $declaresequence "LeaningBackward04"

// $declaresequence "LeaningLeftward01"

// $declaresequence "LeaningLeftward02"

// $declaresequence "LeaningLeftward03"

// $declaresequence "LeaningLeftward04"

// $declaresequence "LeaningForward01"

// $declaresequence "LeaningForward02"

// $declaresequence "LeaningForward03"

// $declaresequence "LeaningForward04"

// $declaresequence "common_male_body_leans"

// $declaresequence "Death_01"

// $declaresequence "Death_02a"

// $declaresequence "Death_02c"

// $declaresequence "Death_03"

// $declaresequence "Death_05"

// $declaresequence "Death_06"

// $declaresequence "Death_07"

// $declaresequence "Death_08"

// $declaresequence "Death_08b"

// $declaresequence "Death_09"

// $declaresequence "Death_10ab"

// $declaresequence "Death_10b"

// $declaresequence "Death_10c"

// $declaresequence "Death_11_01a"

// $declaresequence "Death_11_01b"

// $declaresequence "Death_11_02a"

// $declaresequence "Death_11_02b"

// $declaresequence "Death_11_02c"

// $declaresequence "Death_11_02d"

// $declaresequence "Death_11_03a"

// $declaresequence "Death_11_03b"

// $declaresequence "Death_11_03c"

// $declaresequence "HeadshotFront"

// $declaresequence "HeadshotBack"

// $declaresequence "DeathRunning_01"

// $declaresequence "DeathRunning_03"

// $declaresequence "DeathRunning_04"

// $declaresequence "DeathRunning_05"

// $declaresequence "DeathRunning_06"

// $declaresequence "DeathRunning_07"

// $declaresequence "DeathRunning_08"

// $declaresequence "DeathRunning_09"

// $declaresequence "DeathRunning_10"

// $declaresequence "DeathRunning_11a"

// $declaresequence "DeathRunning_11b"

// $declaresequence "DeathRunning_11c"

// $declaresequence "DeathRunning_11d"

// $declaresequence "DeathRunning_11e"

// $declaresequence "DeathRunning_11f"

// $declaresequence "DeathRunning_11g"

// $declaresequence "Death_Shotgun_Backward_05"

// $declaresequence "Death_Shotgun_Backward_03"

// $declaresequence "Death_Shotgun_Backward_04"

// $declaresequence "Death_Shotgun_Backward_06"

// $declaresequence "Death_Shotgun_Backward_07"

// $declaresequence "Death_Shotgun_Backward_08"

// $declaresequence "Death_Shotgun_Backward_09"

// $declaresequence "Death_Shotgun_Backward_collapse"

// $declaresequence "Death_shotgun_Forward"

// $declaresequence "Death_Shotgun_Rightward"

// $declaresequence "Death_Shotgun_Rightward01"

// $declaresequence "Death_Shotgun_Rightward02"

// $declaresequence "Death_Shotgun_Leftward"

// $declaresequence "deathpose_front"

// $declaresequence "deathpose_back"

// $declaresequence "deathpose_right"

// $declaresequence "deathpose_left"

// $declaresequence "deathpose_crouch_front"

// $declaresequence "deathpose_crouch_back"

// $declaresequence "deathpose_crouch_right"

// $declaresequence "deathpose_crouch_left"

// $declaresequence "Flinch_01"

// $declaresequence "Flinch_02"

// $declaresequence "Startled_delta_01"

// $declaresequence "Startled_01"

// $declaresequence "Charger_Shove_Leftward"

// $declaresequence "Charger_Shove_Rightward"

// $declaresequence "mudguy_run"

// $declaresequence "Chainsaw_Rshldr"

// $declaresequence "Chainsaw_Head_Down"

// $declaresequence "Chainsaw_Back_Up"

// $declaresequence "Chainsaw_Chest_Up"

// $declaresequence "Chainsaw_Shldrs_Down"

// $declaresequence "Chainsaw_Back_Forward"

// $declaresequence "Chainsaw_Lshldr_Down"

// $declaresequence "Chainsaw_Rshldr_Behind"

// $declaresequence "Chainsaw_Rshldr_Down"

// $declaresequence "Chainsaw_Chest_Up2"

// $declaresequence "Chainsaw_Head_Down2"

// $declaresequence "Chainsaw_Chest_Down"

// $declaresequence "Chainsaw_Lside"

// $declaresequence "Chainsaw_Rhip"

// $declaresequence "Chainsaw_Rside"

// $declaresequence "melee_death_right_01"

// $declaresequence "melee_death_right_02"

// $declaresequence "melee_death_left_01"

// $declaresequence "melee_death_left_02"

// $declaresequence "melee_death_back_01"

// $declaresequence "melee_death_back_02"

// $declaresequence "melee_death_back_03"

// $declaresequence "melee_death_back_04"

// $declaresequence "melee_death_back_05"

// $declaresequence "melee_death_right_01_SLASH"

// $declaresequence "melee_death_right_02_SLASH"

// $declaresequence "melee_death_left_01_SLASH"

// $declaresequence "melee_death_left_02_SLASH"

// $declaresequence "melee_death_back_01_SLASH"

// $declaresequence "melee_death_back_02_SLASH"

// $declaresequence "melee_death_back_03_SLASH"

// $declaresequence "melee_death_back_04_SLASH"

// $declaresequence "melee_death_back_05_SLASH"

// $declaresequence "Idle_Neutral_04"

// $declaresequence "Idle_Neutral_05"

// $declaresequence "exp_idle_01"

// $declaresequence "exp_idle_02"

// $declaresequence "exp_idle_03"

// $declaresequence "exp_idle_04"

// $declaresequence "exp_idle_05"

// $declaresequence "exp_idle_06"

// $declaresequence "exp_angry_01"

// $declaresequence "exp_angry_02"

// $declaresequence "exp_angry_03"

// $declaresequence "exp_angry_04"

// $declaresequence "exp_angry_05"

// $declaresequence "exp_angry_06"

/* $sequence "reference" {
	"common_female_tanktop_jeans_rain_anims\reference.smd"
	fadein 0.2
	fadeout 0.2
	fps 1
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
}

$sequence "proportions" {
	"a_proportions"
	autoplay
	predelta
	fadein 0.2
	fadeout 0.2
} */

$includemodel "infected/anim_common.mdl"
$includemodel "infected/anim_common_vomit.mdl"
$includemodel "infected/anim_common_male_exp.mdl"

/* $collisionjoints "common_female_tanktop_jeans_rain_physics.smd"
{
	$mass 100
	$inertia 10
	$damping 0.05
	$rotdamping 0.01
	$rootbone " "


	$jointconstrain "ValveBiped.Bip01_R_Thigh" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_R_Thigh" y limit -10 15 0
	$jointconstrain "ValveBiped.Bip01_R_Thigh" z limit -55 25 0

	$jointconstrain "ValveBiped.Bip01_R_Calf" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_R_Calf" y limit -5 5 0
	$jointconstrain "ValveBiped.Bip01_R_Calf" z limit 0 120 0

	$jointconstrain "ValveBiped.Bip01_L_Thigh" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_L_Thigh" y limit -15 10 0
	$jointconstrain "ValveBiped.Bip01_L_Thigh" z limit -55 25 0

	$jointconstrain "ValveBiped.Bip01_L_Calf" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_L_Calf" y limit -5 5 0
	$jointconstrain "ValveBiped.Bip01_L_Calf" z limit 0 120 0

	$jointconstrain "ValveBiped.Bip01_L_Foot" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_L_Foot" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_L_Foot" z limit -20 25 0

	$jointconstrain "ValveBiped.Bip01_Spine2" x limit -15 15 0
	$jointconstrain "ValveBiped.Bip01_Spine2" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_Spine2" z limit -25 30 0

	$jointconstrain "ValveBiped.Bip01_R_UpperArm" x limit -15 20 0
	$jointconstrain "ValveBiped.Bip01_R_UpperArm" y limit -40 40 0
	$jointconstrain "ValveBiped.Bip01_R_UpperArm" z limit -122 50 0

	$jointconstrain "ValveBiped.Bip01_R_Forearm" x limit -40 15 0
	$jointconstrain "ValveBiped.Bip01_R_Forearm" y limit 0 0 0
	$jointconstrain "ValveBiped.Bip01_R_Forearm" z limit -120 10 0

	$jointconstrain "ValveBiped.Bip01_L_UpperArm" x limit -15 20 0
	$jointconstrain "ValveBiped.Bip01_L_UpperArm" y limit -40 40 0
	$jointconstrain "ValveBiped.Bip01_L_UpperArm" z limit -122 50 0

	$jointconstrain "ValveBiped.Bip01_L_Forearm" x limit -40 15 0
	$jointconstrain "ValveBiped.Bip01_L_Forearm" y limit 0 0 0
	$jointconstrain "ValveBiped.Bip01_L_Forearm" z limit -120 10 0

	$jointconstrain "ValveBiped.Bip01_L_Hand" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_L_Hand" y limit -35 35 0
	$jointconstrain "ValveBiped.Bip01_L_Hand" z limit -50 50 0

	$jointconstrain "ValveBiped.Bip01_Head1" x limit -61 61 0
	$jointconstrain "ValveBiped.Bip01_Head1" y limit -44 44 0
	$jointconstrain "ValveBiped.Bip01_Head1" z limit -32 50 0

	$jointconstrain "ValveBiped.Bip01_R_Hand" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_R_Hand" y limit -35 35 0
	$jointconstrain "ValveBiped.Bip01_R_Hand" z limit -50 50 0

	$jointconstrain "ValveBiped.Bip01_R_Foot" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_R_Foot" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_R_Foot" z limit -20 25 0
} */
