// Created by Crowbar 0.74

$modelname "deadbodies/dead_military_male01.mdl"

$model "Associates" "tenshi_pm_reference.smd" {

	mouth 0 "mouth" "ValveBiped.Bip01_Head1" 0 1 0

	flexfile "dead_military_male01.vta" 
	{
		defaultflex frame 0
		flex "eye_star" frame 1
		flex "eye_love" frame 2
		flex "eye_collapse" frame 3
		flex "eye_scared" frame 4
		flex "brow_happy" frame 5
		flex "brow_serious" frame 6
		flex "brow_angry" frame 7
		flex "brow_sad" frame 8
		flex "brow_sleepy" frame 9
		flex "brow_up" frame 10
		flex "brow_down" frame 11
		flex "brow_front" frame 12
		flex "face_bigger" frame 13
		flex "blink" frame 14
		flex "eye_closeL" frame 15
		flex "eye_closeR" frame 16
		flex "eye_happy" frame 17
		flex "eye_happyL" frame 18
		flex "eye_happyR" frame 19
		flex "eye_cute" frame 20
		flex "eye_cuteL" frame 21
		flex "eye_cuteR" frame 22
		flex "eye_down" frame 23
		flex "eye_downL" frame 24
		flex "eye_downR" frame 25
		flex "eye_nagomi" frame 26
		flex "eye_sharp" frame 27
		flex "eye_sharpL" frame 28
		flex "eye_sharpR" frame 29
		flex "eye_taunt" frame 30
		flex "eye_bigger" frame 31
		flex "mouth_a" frame 32
		flex "mouth_i" frame 33
		flex "mouth_u" frame 34
		flex "mouth_e" frame 35
		flex "mouth_o" frame 36
		flex "mouth_laugh" frame 37
		flex "mouth_unhappy" frame 38
		flex "mouth_triangle" frame 39
		flex "mouth_meow" frame 40
		flex "mouth_meow2" frame 41
		flex "mouth_happy" frame 42
		flex "mouth_surprised" frame 43
		flex "mouth_naughty" frame 44
		flex "mouth_tongue" frame 45
		flex "mouth_gasp" frame 46
		flex "mouth_grin" frame 47
		flex "mouth_curious" frame 48
		flex "mouth_smile" frame 49
		flex "mouth_sad" frame 50
		flex "foots_no" frame 51
		flex "eye_tear" frame 52
		flex "eye_reflective" frame 53
		flex "face_red" frame 54
		flex "face_red2" frame 55
	}

	flexcontroller mouth_a range 0 1 "mouth_a"
	flexcontroller mouth_i range 0 1 "mouth_i"
	flexcontroller mouth_u range 0 1 "mouth_u"
	flexcontroller mouth_e range 0 1 "mouth_e"
	flexcontroller mouth_o range 0 1 "mouth_o"
	flexcontroller mouth_laugh range 0 1 "mouth_laugh"
	flexcontroller mouth_unhappy range 0 1 "mouth_unhappy"
	flexcontroller mouth_triangle range 0 1 "mouth_triangle"
	flexcontroller mouth_meow range 0 1 "mouth_meow"
	flexcontroller mouth_meow2 range 0 1 "mouth_meow2"
	flexcontroller mouth_happy range 0 1 "mouth_happy"
	flexcontroller mouth_surprised range 0 1 "mouth_surprised"
	flexcontroller mouth_naughty range 0 1 "mouth_naughty"
	flexcontroller mouth_tongue range 0 1 "mouth_tongue"
	flexcontroller mouth_gasp range 0 1 "mouth_gasp"
	flexcontroller mouth_grin range 0 1 "mouth_grin"
	flexcontroller mouth_curious range 0 1 "mouth_curious"
	flexcontroller face_bigger range 0 1 "face_bigger"
	flexcontroller mouth_smile range 0 1 "mouth_smile"
	flexcontroller mouth_sad range 0 1 "mouth_sad"
	flexcontroller eyelid range 0 1 "blink"
	flexcontroller eye_closeL range 0 1 "eye_closeL"
	flexcontroller eye_closeR range 0 1 "eye_closeR"
	flexcontroller eye_happy range 0 1 "eye_happy"
	flexcontroller eye_happyL range 0 1 "eye_happyL"
	flexcontroller eye_happyR range 0 1 "eye_happyR"
	flexcontroller eye_cute range 0 1 "eye_cute"
	flexcontroller eye_cuteL range 0 1 "eye_cuteL"
	flexcontroller eye_cuteR range 0 1 "eye_cuteR"
	flexcontroller eye_down range 0 1 "eye_down"
	flexcontroller eye_downL range 0 1 "eye_downL"
	flexcontroller eye_downR range 0 1 "eye_downR"
	flexcontroller eye_nagomi range 0 1 "eye_nagomi"
	flexcontroller eye_sharp range 0 1 "eye_sharp"
	flexcontroller eye_sharpL range 0 1 "eye_sharpL"
	flexcontroller eye_sharpR range 0 1 "eye_sharpR"
	flexcontroller eye_taunt range 0 1 "eye_taunt"
	flexcontroller eye_bigger range 0 1 "eye_bigger"
	flexcontroller eye_tear range 0 1 "eye_tear"
	flexcontroller eye_star range 0 1 "eye_star"
	flexcontroller eye_love range 0 1 "eye_love"
	flexcontroller eye_collapse range 0 1 "eye_collapse"
	flexcontroller eye_reflective range 0 1 "eye_reflective"
	flexcontroller eye_scared range 0 1 "eye_scared"
	flexcontroller brow_happy range 0 1 "brow_happy"
	flexcontroller brow_serious range 0 1 "brow_serious"
	flexcontroller brow_angry range 0 1 "brow_angry"
	flexcontroller brow_sad range 0 1 "brow_sad"
	flexcontroller brow_sleepy range 0 1 "brow_sleepy"
	flexcontroller brow_up range 0 1 "brow_up"
	flexcontroller brow_down range 0 1 "brow_down"
	flexcontroller brow_front range 0 1 "brow_front"
	flexcontroller foots_no range 0 1 "foots_no"
	flexcontroller face_red range 0 1 "face_red"
	flexcontroller face_red2 range 0 1 "face_red2"

	%mouth_a = mouth_a
	%mouth_i = mouth_i
	%mouth_u = mouth_u
	%mouth_e = mouth_e
	%mouth_o = mouth_o
	%mouth_laugh = mouth_laugh
	%mouth_unhappy = mouth_unhappy
	%mouth_triangle = mouth_triangle
	%mouth_meow = mouth_meow
	%mouth_meow2 = mouth_meow2
	%mouth_happy = mouth_happy
	%mouth_surprised = mouth_surprised
	%mouth_naughty = mouth_naughty
	%mouth_tongue = mouth_tongue
	%mouth_gasp = mouth_gasp
	%mouth_grin = mouth_grin
	%mouth_curious = mouth_curious
	%face_bigger = face_bigger
	%mouth_smile = mouth_smile
	%mouth_sad = mouth_sad
	%blink = blink
	%eye_closeL = eye_closeL
	%eye_closeR = eye_closeR
	%eye_happy = eye_happy
	%eye_happyL = eye_happyL
	%eye_happyR = eye_happyR
	%eye_cute = eye_cute
	%eye_cuteL = eye_cuteL
	%eye_cuteR = eye_cuteR
	%eye_down = eye_down
	%eye_downL = eye_downL
	%eye_downR = eye_downR
	%eye_nagomi = eye_nagomi
	%eye_sharp = eye_sharp
	%eye_sharpL = eye_sharpL
	%eye_sharpR = eye_sharpR
	%eye_taunt = eye_taunt
	%eye_bigger = eye_bigger
	%eye_tear = eye_tear
	%eye_star = eye_star
	%eye_love = eye_love
	%eye_collapse = eye_collapse
	%eye_reflective = eye_reflective
	%eye_scared = eye_scared
	%brow_happy = brow_happy
	%brow_serious = brow_serious
	%brow_angry = brow_angry
	%brow_sad = brow_sad
	%brow_sleepy = brow_sleepy
	%brow_up = brow_up
	%brow_down = brow_down
	%brow_front = brow_front
	%foots_no = foots_no
	%face_red = face_red
	%face_red2 = face_red2
}
$bodygroup "Hair"
{
	studio "tenshi_pm_tenshi_hair.smd"
}
$bodygroup "Hat"
{
	studio "tenshi_pm_tenshi_hat.smd"
	blank
}
$bodygroup "Boots"
{
	studio "tenshi_pm_tenshi_boots.smd"
	studio "tenshi_pm_legs.smd"
}
$bodygroup "Cloth"
{
	studio "tenshi_pm_tenshi_cloth.smd"
}

$surfaceprop "flesh"

$contents "solid"

$illumposition -0.014 1.663 36.346

$ambientboost

$mostlyopaque

$cdmaterials "models\meowmeow\deadbodies\tenshi\"

$attachment "eyes" "ValveBiped.Bip01_Head1" 3.41 -3.93 -0.08 rotate 0 -80.1 -90
$attachment "mouth" "ValveBiped.Bip01_Head1" 0.8 -5.8 -0.15 rotate 0 -80 -90
$attachment "chest" "ValveBiped.Bip01_Spine2" 5 4 0 rotate 0 90 90
$attachment "forward" "ValveBiped.forward" 0 0 0 rotate 0 0 0
$attachment "anim_attachment_RH" "ValveBiped.Anim_Attachment_RH" 0 0 0 rotate -90 -90 0
$attachment "anim_attachment_LH" "ValveBiped.Anim_Attachment_LH" 0 0 0 rotate -90 -90 0
$attachment "anim_attachment_head" "ValveBiped.Bip01_Head1" 0 0 0 rotate -90 -90 0
$attachment "Head" "ValveBiped.Bip01_Head1" 0 0 0 rotate 0 0 0
$attachment "RArm" "ValveBiped.Bip01_R_UpperArm" 0 0 0 rotate 0 0 0
$attachment "LArm" "ValveBiped.Bip01_L_UpperArm" 0 0 0 rotate 0 0 0
$attachment "RLeg" "ValveBiped.Bip01_R_Thigh" 0 0 0 rotate 0 0 0
$attachment "LLeg" "ValveBiped.Bip01_L_Thigh" 0 0 0 rotate 0 0 0
$attachment "lfoot" "ValveBiped.Bip01_L_Calf" -3.09 -70.42 -5.56 rotate 16.55 0 0
$attachment "rfoot" "ValveBiped.Bip01_R_Calf" 16.55 0 0 rotate 3.09 -70.42 6.2
$attachment "severed_Head" "ValveBiped.Bip01_Head1" 0 0 0 rotate 0 -41.08 -90
$attachment "severed_RArm" "ValveBiped.Bip01_R_UpperArm" 11.1 -0.3 0.4 rotate 0 0 90
$attachment "severed_LArm" "ValveBiped.Bip01_L_UpperArm" 8.5 -0.2 -0.4 rotate 0 0 90
$attachment "severed_RLeg" "ValveBiped.Bip01_R_Thigh" 13.5 -0.8 0 rotate 0 0 90
$attachment "severed_LLeg" "ValveBiped.Bip01_L_Thigh" 14 -0.7 0 rotate 0 0 90
$attachment "baton" "ValveBiped.Bip01_Pelvis" -6 1.5 7.5 rotate 0 75 -160

$cbox 0 0 0 0 0 0

$bbox -13 -13 0 13 13 72

$hboxset "default"
$hbox 3 "ValveBiped.Bip01_Pelvis" -6 -4.5 -4.5 6 4.5 4.5
$hbox 6 "ValveBiped.Bip01_L_Thigh" -1 -3.4 -2.85 17 2.6 2.15
$hbox 6 "ValveBiped.Bip01_L_Calf" 0.5 -1.5 -2 15.5 2.5 2
$hbox 7 "ValveBiped.Bip01_R_Thigh" -1 -3.4 -2.25 17 2.6 2.75
$hbox 7 "ValveBiped.Bip01_R_Calf" 0.5 -1.5 -2 15.5 2.5 2
$hbox 3 "ValveBiped.Bip01_Spine1" -3.5 -2 -5 1.5 6 5
$hbox 2 "ValveBiped.Bip01_Spine2" -3 -2.25 -4.5 10 6.25 4.5
$hbox 1 "ValveBiped.Bip01_Head1" -1 -4.5 -4.3 9 4.5 3.7
$hbox 4 "ValveBiped.Bip01_L_UpperArm" -2 -1.9 -1.8 9 1.7 1.8
$hbox 4 "ValveBiped.Bip01_L_Forearm" -0.5 -1.5 -1.5 10.5 1.5 1.5
$hbox 4 "ValveBiped.Bip01_L_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$hbox 5 "ValveBiped.Bip01_R_UpperArm" -2 -1.9 -1.8 9 1.7 1.8
$hbox 5 "ValveBiped.Bip01_R_Forearm" -0.5 -1.5 -1.5 10.5 1.5 1.5
$hbox 5 "ValveBiped.Bip01_R_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$hbox 7 "ValveBiped.Bip01_R_Foot" -1.5 -1.5 -1.75 5.5 1.5 1.75
$hbox 6 "ValveBiped.Bip01_L_Foot" -1.5 -1.5 -1.75 5.5 1.5 1.75
$hbox 0 "ValveBiped.Bip01_L_Toe0" -0.5 -1.5 -1.5 2.5 1.5 1.5
$hbox 0 "ValveBiped.Bip01_R_Toe0" -0.5 -1.5 -1.5 2.5 1.5 1.5
$skipboneinbbox

$definebone "ValveBiped.Bip01_Pelvis" "" 0.005735 -0.710612 35.671192 0 0 89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine" "ValveBiped.Bip01_Pelvis" 0.000004 3.939247 -1.580135 -1.602964 89.999982 89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine1" "ValveBiped.Bip01_Spine" 3.588203 0 0 0 -6.452308 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine2" "ValveBiped.Bip01_Spine1" 3.38298 0 0 0 -0.723932 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 7.050217 0 0 0 8.927427 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Neck1" "ValveBiped.Bip01_Spine4" 2.971947 0 0 0 13.008776 179.999841 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Head1" "ValveBiped.Bip01_Neck1" 3.226833 0.000002 0 0 6.359662 0 0 0 0 0 0 0
$definebone "ValveBiped.forward" "ValveBiped.Bip01_Head1" 0 0 0 0 -75.838077 -89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 1.892315 0.84854 0.797221 -76.440397 166.164446 93.871156 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 4.660078 0.000004 0 4.983816 -24.445087 -82.125594 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 9.017756 -0.000001 -0.000011 0.499232 -2.346035 0.04068 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 9.086874 0 0.000004 0.000012 -0.000001 -3.296971 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 9.086874 0 0.000004 -2.211893 2.080008 86.25404 0 0 0 0 0 0
$definebone "ValveBiped.Anim_Attachment_LH" "ValveBiped.Bip01_L_Hand" 2.211563 -1.415165 0 0.000037 90.000023 90.000023 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 3.056105 0.221104 -0.602438 -0.275879 -14.783647 3.947393 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.445406 0 0 3.305452 7.195479 2.441488 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 0.793354 0.000015 0 -5.6944 -11.672084 14.315463 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.11434 0.126087 0.058993 -1.50728 -9.825038 8.155422 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 1.68424 -0.000019 0 2.247712 3.075742 -2.069869 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 0.881786 0.000004 0 -0.324984 -5.671956 -0.071335 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.127102 -0.014267 0.65663 -8.549793 -5.874893 17.354259 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.346233 -0.000008 -0.000004 4.8553 -8.63844 -1.191295 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 0.790057 0 0.000004 1.158634 4.255753 1.318146 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 3.147793 -0.110989 -1.42888 -5.557061 -6.08425 12.274188 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 1.0074 -0.000011 -0.000004 4.457553 -4.936446 -23.44841 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.56195 -0.000015 0.000001 -0.735273 -3.248742 11.125868 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.172184 -0.371784 0.695803 -43.90937 -30.246113 -4.282976 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.151196 0.000008 -0.00001 2.505715 5.983326 -9.685048 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 0.909058 -0.000006 0.000002 6.207941 -0.850455 -18.318149 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Elbow" "ValveBiped.Bip01_L_UpperArm" 9.017769 0 -0.000031 0.000014 -5.732558 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 1.892315 0.848547 -0.797174 76.440568 166.163736 -97.982404 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 4.660077 -0.000015 0 -3.263511 -24.715299 85.874056 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 9.010712 -0.000001 0.000008 -0.4966 -2.390896 -0.040278 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 9.079771 -0.000001 0.000019 2.240359 1.70942 -86.05843 0 0 0 0 0 0
$definebone "ValveBiped.Anim_Attachment_RH" "ValveBiped.Bip01_R_Hand" 2.230804 -1.427517 0 0 -89.999962 -89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.080542 0.081699 -0.057919 1.208882 -6.83054 -5.343462 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 1.774378 -0.000031 0 0.107145 -16.749924 4.843611 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 0.911787 -0.000004 0 -0.477274 14.465383 -0.449601 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.090347 -0.067162 -0.659407 7.310655 -6.793639 -17.159225 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.423207 0.000008 0.000004 -3.723589 -8.902694 0.072471 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 0.821628 -0.000023 0.000002 -5.769508 6.446152 2.364649 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 3.025173 0.184662 0.764039 3.00837 -10.262212 -10.041886 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.509716 -0.000015 -0.000001 -2.62128 -4.269821 -0.253765 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 0.818399 -0.000019 -0.000002 0.943205 -1.034903 -4.677112 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 2.898108 0.049751 1.316749 -0.078096 -14.256647 -8.301067 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 1.037357 0 0 7.709777 3.155491 -15.763612 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.580746 -0.000023 0.00001 -7.519146 -3.918937 -0.323948 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.158314 -0.442905 -0.732248 41.222422 -28.829593 103.37895 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.161232 -0.000002 0.00001 3.174112 5.134397 13.009006 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 0.916969 0.000015 -0.000011 4.230993 -10.231579 1.169521 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 9.079771 -0.000001 0.000011 -0.000022 0 3.734023 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Thigh" "ValveBiped.Bip01_Pelvis" 3.725333 -0.000004 -0.000003 1.780925 -92.308197 -89.999982 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Calf" "ValveBiped.Bip01_L_Thigh" 15.193455 0 0 -0.991561 2.959556 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Foot" "ValveBiped.Bip01_L_Calf" 17.0256 0.052295 0.003148 -4.40255 -70.478277 0.515032 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Thigh" "ValveBiped.Bip01_Pelvis" -3.725332 0.000008 0.000006 1.781899 -87.560498 -90.027542 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Calf" "ValveBiped.Bip01_R_Thigh" 15.193434 0 0 1.02697 2.959557 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Foot" "ValveBiped.Bip01_R_Calf" 17.025562 0.052282 -0.003058 2.767386 -70.654632 -0.761404 0 0 0 0 0 0
$definebone "p_skirt_n_helper" "ValveBiped.Bip01_Pelvis" 0.00085 0.159142 -5.185494 1.450249 -90.000016 90.000016 0 0 0 0 0 0
$definebone "p_skirt_nw_helper" "ValveBiped.Bip01_Pelvis" -4.416689 0.011898 -4.249946 -1.823839 -95.850169 89.893868 0 0 0 0 0 0
$definebone "j_hair_r_01" "ValveBiped.Bip01_Head1" 4.439457 -1.917301 3.67986 6.434699 -175.87259 -180.000005 0 0 0 0 0 0
$definebone "j_hair_r_02" "j_hair_r_01" 4.703285 -0.000008 -0.000005 6.032786 -32.820633 -0.019312 0 0 0 0 0 0
$definebone "j_hair_r_03" "j_hair_r_02" 5.480251 0.000002 0.000002 -0.000001 9.560772 -0.000002 0 0 0 0 0 0
$definebone "j_hair_l_01" "ValveBiped.Bip01_Head1" 4.674915 -2.010233 -3.449562 -5.349473 -175.282871 -0.000229 0 0 0 0 0 0
$definebone "j_hair_l_02" "j_hair_l_01" 5.11594 0.00001 -0.000001 7.24797 31.966802 0.022576 0 0 0 0 0 0
$definebone "j_hair_l_03" "j_hair_l_02" 5.213482 -0.000008 0.000003 -0.000002 -9.066712 0.000002 0 0 0 0 0 0
$definebone "j_hair_f_01" "ValveBiped.Bip01_Head1" 7.148788 -3.165135 0.000008 0.000172 -141.072694 -0.000115 0 0 0 0 0 0
$definebone "j_hair_f_02" "j_hair_f_01" 2.826138 -0.000015 0.000001 0 -40.54278 0 0 0 0 0 0 0
$definebone "j_hair_b_01" "ValveBiped.Bip01_Head1" 2.002647 4.890163 0.000036 -0.000057 174.453673 -0.000172 0 0 0 0 0 0
$definebone "j_hair_b_02" "j_hair_b_01" 5.923714 -0.000011 0 0 9.927525 0 0 0 0 0 0 0
$definebone "j_hair_b_03" "j_hair_b_02" 5.653236 -0.000002 0 0 5.422931 0 0 0 0 0 0 0
$definebone "j_hair_b_04" "j_hair_b_03" 6.246349 -0.000008 0 0 -3.671628 0 0 0 0 0 0 0
$definebone "j_hair_bl_01" "j_hair_b_01" 8.798267 1.402256 -4.517012 0.000057 8.639342 0.000057 0 0 0 0 0 0
$definebone "j_hair_bl_02" "j_hair_bl_01" 7.837658 -0.000035 0 0 17.13264 0 0 0 0 0 0 0
$definebone "j_hair_br_01" "j_hair_b_01" 8.809624 1.405354 4.524812 0.000057 8.858498 0.000286 0 0 0 0 0 0
$definebone "j_hair_br_02" "j_hair_br_01" 7.681396 -0.000042 0 0.000057 15.942667 -0.000229 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Toe0" "ValveBiped.Bip01_L_Foot" 5.913433 -0.000002 0 0.053515 -28.677396 -0.638619 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Ankle" "ValveBiped.Bip01_L_Calf" 15.867319 0 0 0 -0.000001 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Toe0" "ValveBiped.Bip01_R_Foot" 5.913435 -0.000003 0 -0.354375 -28.587328 -4.506371 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Ankle" "ValveBiped.Bip01_R_Calf" 15.867306 0 0 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Shoulder" "ValveBiped.Bip01_L_UpperArm" 1.216091 0 0 0.000012 -0.000001 -9.00873 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Trapezius" "ValveBiped.Bip01_L_Clavicle" 3.994339 0.000019 0.000001 0 -0.000003 0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Shoulder" "ValveBiped.Bip01_R_UpperArm" 1.215141 0 0.000008 -0.000015 0 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Trapezius" "ValveBiped.Bip01_R_Clavicle" 3.994339 -0.000008 0 0 -0.000005 -0.000001 0 0 0 0 0 0
$definebone "p_bowknot_01" "ValveBiped.Bip01_Spine4" 2.452606 4.138953 0.000845 0 66.790494 -179.999964 0 0 0 0 0 0
$definebone "p_bowknot_02" "ValveBiped.Bip01_Spine1" 1.609295 -0.975732 0.000843 -0.000019 -120.284904 -179.999937 0 0 0 0 0 0
$definebone "p_skirt_e_helper" "ValveBiped.Bip01_L_Thigh" -0.044476 0.742047 3.222854 -7.68491 -1.780925 -90.000098 0 0 0 0 0 0
$definebone "p_skirt_e_01" "p_skirt_e_helper" 6.531517 -0.000002 0 0 -7.152119 0 0 0 0 0 0 0
$definebone "p_skirt_e_02" "p_skirt_e_01" 4.93721 0 0.000001 0 -2.031422 0 0 0 0 0 0 0
$definebone "p_skirt_se_helper" "ValveBiped.Bip01_L_Thigh" -0.459084 -3.221061 1.004059 -11.669601 -2.430201 -179.868647 0 0 0 0 0 0
$definebone "p_skirt_se_01" "p_skirt_se_helper" 6.550079 0 0 -0.000003 2.726305 0 0 0 0 0 0 0
$definebone "p_skirt_se_02" "p_skirt_se_01" 5.690502 0 0.000002 -0.000002 5.778393 0 0 0 0 0 0 0
$definebone "p_skirt_w_helper" "ValveBiped.Bip01_R_Thigh" 0.26564 0.733831 -2.956548 9.150252 -1.777487 -89.971965 0 0 0 0 0 0
$definebone "p_skirt_w_01" "p_skirt_w_helper" 6.547434 0.000029 0 0 7.539607 -0.000057 0 0 0 0 0 0
$definebone "p_skirt_w_02" "p_skirt_w_01" 4.972834 0.000003 0 0 2.044599 0 0 0 0 0 0 0
$definebone "p_skirt_sw_helper" "ValveBiped.Bip01_R_Thigh" -0.643188 -2.929194 -1.114202 11.994242 -4.946174 -179.689655 0 0 0 0 0 0
$definebone "p_skirt_sw_01" "p_skirt_sw_helper" 6.324804 0.000001 0 0.000057 0.078612 -0.000401 0 0 0 0 0 0
$definebone "p_skirt_sw_02" "p_skirt_sw_01" 6.0956 0 0.000001 0.000001 5.74047 0 0 0 0 0 0 0
$definebone "p_skirt_n_01" "p_skirt_n_helper" 6.049822 0.000001 0 0 -5.338706 0 0 0 0 0 0 0
$definebone "p_skirt_n_02" "p_skirt_n_01" 6.476076 -0.000002 0 0 -2.008448 0 0 0 0 0 0 0
$definebone "p_skirt_nw_01" "p_skirt_nw_helper" 5.955616 0 -0.000002 0 -5.724536 0 0 0 0 0 0 0
$definebone "p_skirt_nw_02" "p_skirt_nw_01" 6.432493 0.000001 0 0 -0.487014 0 0 0 0 0 0 0
$definebone "p_skirt_ne_helper" "ValveBiped.Bip01_Pelvis" 3.827445 -0.150501 -4.392723 0.615872 -81.585237 90.643126 0 0 0 0 0 0
$definebone "p_skirt_ne_01" "p_skirt_ne_helper" 5.646536 0 0.000002 0.000003 -1.663067 0 0 0 0 0 0 0
$definebone "p_skirt_ne_02" "p_skirt_ne_01" 6.151291 0.000013 0 0.000003 0.081016 0 0 0 0 0 0 0

$bonemerge "ValveBiped.Bip01_Pelvis"
$bonemerge "ValveBiped.Bip01_Spine"
$bonemerge "ValveBiped.Bip01_Spine1"
$bonemerge "ValveBiped.Bip01_Spine2"
$bonemerge "ValveBiped.Bip01_Spine4"
$bonemerge "ValveBiped.Bip01_R_Clavicle"
$bonemerge "ValveBiped.Bip01_R_UpperArm"
$bonemerge "ValveBiped.Bip01_R_Forearm"
$bonemerge "ValveBiped.Bip01_R_Hand"

$jigglebone "j_hair_r_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_r_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_r_03"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_l_03"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_f_01"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_f_02"
{
	is_flexible
	{
		length 25
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 8
		yaw_stiffness 50
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -28 12
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 28
	}
}
$jigglebone "j_hair_b_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_03"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_b_04"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_bl_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_01"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "j_hair_br_02"
{
	is_flexible
	{
		length 30
		tip_mass 0
		pitch_stiffness 50
		pitch_damping 7
		yaw_stiffness 50
		yaw_damping 7
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -100.000001 10
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 50
	}
}
$jigglebone "p_bowknot_01"
{
	is_flexible
	{
		length 5
		tip_mass 0
		pitch_stiffness 120
		pitch_damping 6
		yaw_stiffness 120
		yaw_damping 6
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -2 39.999999
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 39.999999
	}
}
$jigglebone "p_bowknot_02"
{
	is_flexible
	{
		length 5
		tip_mass 0
		pitch_stiffness 120
		pitch_damping 6
		yaw_stiffness 120
		yaw_damping 6
		allow_length_flex
		along_stiffness 100
		along_damping 0
		pitch_constraint -2 39.999999
		pitch_friction 0
		pitch_bounce 0
		angle_constraint 39.999999
	}
}
$jigglebone "p_skirt_e_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_e_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_se_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_w_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_w_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_sw_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_sw_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_n_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_n_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_nw_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_nw_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_ne_01"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}
$jigglebone "p_skirt_ne_02"
{
	is_flexible
	{
		length 20
		tip_mass 100
		pitch_stiffness 80
		pitch_damping 8
		yaw_stiffness 80
		yaw_damping 8
		allow_length_flex
		along_stiffness 100
		along_damping 0
		angle_constraint 15
	}
}

$sequence "idle" {
	"dead_military_male01_anims\idle.smd"
	activity "act_idle" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ragdoll" {
	"dead_military_male01_anims\ragdoll.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}


$collisionjoints "dead_military_male01_physics.smd"
{
	$mass 0
	$inertia 10
	$damping 0.05
	$rotdamping 0.01
	$rootbone " "


	$jointconstrain "ValveBiped.Bip01_R_Thigh" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_R_Thigh" y limit -10 15 0
	$jointconstrain "ValveBiped.Bip01_R_Thigh" z limit -55 25 0

	$jointconstrain "ValveBiped.Bip01_R_Calf" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_R_Calf" y limit -5 5 0
	$jointconstrain "ValveBiped.Bip01_R_Calf" z limit 0 120 0

	$jointconstrain "ValveBiped.Bip01_L_Thigh" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_L_Thigh" y limit -15 10 0
	$jointconstrain "ValveBiped.Bip01_L_Thigh" z limit -55 25 0

	$jointconstrain "ValveBiped.Bip01_L_Calf" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_L_Calf" y limit -5 5 0
	$jointconstrain "ValveBiped.Bip01_L_Calf" z limit 0 120 0

	$jointconstrain "ValveBiped.Bip01_L_Foot" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_L_Foot" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_L_Foot" z limit -20 25 0

	$jointconstrain "ValveBiped.Bip01_Spine2" x limit -15 15 0
	$jointconstrain "ValveBiped.Bip01_Spine2" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_Spine2" z limit -25 30 0

	$jointconstrain "ValveBiped.Bip01_R_UpperArm" x limit -15 20 0
	$jointconstrain "ValveBiped.Bip01_R_UpperArm" y limit -40 40 0
	$jointconstrain "ValveBiped.Bip01_R_UpperArm" z limit -122 50 0

	$jointconstrain "ValveBiped.Bip01_R_Forearm" x limit -40 15 0
	$jointconstrain "ValveBiped.Bip01_R_Forearm" y limit 0 0 0
	$jointconstrain "ValveBiped.Bip01_R_Forearm" z limit -120 10 0

	$jointconstrain "ValveBiped.Bip01_L_UpperArm" x limit -15 20 0
	$jointconstrain "ValveBiped.Bip01_L_UpperArm" y limit -40 40 0
	$jointconstrain "ValveBiped.Bip01_L_UpperArm" z limit -122 50 0

	$jointconstrain "ValveBiped.Bip01_L_Forearm" x limit -40 15 0
	$jointconstrain "ValveBiped.Bip01_L_Forearm" y limit 0 0 0
	$jointconstrain "ValveBiped.Bip01_L_Forearm" z limit -120 10 0

	$jointconstrain "ValveBiped.Bip01_L_Hand" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_L_Hand" y limit -35 35 0
	$jointconstrain "ValveBiped.Bip01_L_Hand" z limit -50 50 0

	$jointconstrain "ValveBiped.Bip01_Head1" x limit -61 61 0
	$jointconstrain "ValveBiped.Bip01_Head1" y limit -44 44 0
	$jointconstrain "ValveBiped.Bip01_Head1" z limit -32 50 0

	$jointconstrain "ValveBiped.Bip01_R_Hand" x limit -25 25 0
	$jointconstrain "ValveBiped.Bip01_R_Hand" y limit -35 35 0
	$jointconstrain "ValveBiped.Bip01_R_Hand" z limit -50 50 0

	$jointconstrain "ValveBiped.Bip01_R_Foot" x limit -10 10 0
	$jointconstrain "ValveBiped.Bip01_R_Foot" y limit -20 20 0
	$jointconstrain "ValveBiped.Bip01_R_Foot" z limit -20 25 0
}

$collisiontext
{
	animatedfriction 
	{
		"animfrictionmin" "100.000000"
		"animfrictionmax" "500.000000"
		"animfrictiontimein" "0.100000"
		"animfrictiontimeout" "0.200000"
		"animfrictiontimehold" "1.000000"
	}
	editparams 
	{
		"rootname" "valvebiped.bip01_pelvis"
		"totalmass" "100.000000"
	}
}
