// Created by Crowbar 0.74

$modelname "hybridPhysx/airliner_fuselage_secondary_4.mdl"

$bodygroup "studio"
{
	studio "airliner_fuselage_secondary_4.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0 "baked_fuselage_debris_secondary_385"

$cdmaterials "models\hybridPhysx\"


$cbox 0 0 0 0 0 0

$bbox -2269.711 2138.863 1106.752 -716.442 2302.364 1324.371

$definebone "airliner_fuselage_secondary_4" "" 4780.613281 1023.561646 3882.923828 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_373" "airliner_fuselage_secondary_4" -55.368164 73.290405 104.115479 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_374" "airliner_fuselage_secondary_4" -32.720703 94.760132 173.218018 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_375" "airliner_fuselage_secondary_4" -52.373047 76.338257 481.863281 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_376" "airliner_fuselage_secondary_4" -38.635742 -74.108765 638.20459 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_377" "airliner_fuselage_secondary_4" -32.989258 -89.615112 530.756348 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_378" "airliner_fuselage_secondary_4" 12.555664 -107.444824 513.473633 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_379" "airliner_fuselage_secondary_4" -54.992188 -69.33197 583.211914 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_380" "airliner_fuselage_secondary_4" -32.720703 94.755493 52.408203 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_381" "airliner_fuselage_secondary_4" 8.588867 107.159302 42.226074 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_382" "airliner_fuselage_secondary_4" -9.615234 99.452759 -274.158203 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_383" "airliner_fuselage_secondary_4" 4.5625 106.772461 -341.021484 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_384" "airliner_fuselage_secondary_4" -32.92334 94.717407 -323.465088 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_385" "airliner_fuselage_secondary_4" -78.663574 -24.918823 -202.398926 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_386" "airliner_fuselage_secondary_4" -69.567383 -51.370483 -234.728516 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_387" "airliner_fuselage_secondary_4" -79.656738 4.225586 -461.076172 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_388" "airliner_fuselage_secondary_4" -69.932617 -51.063721 -128.446289 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_389" "airliner_fuselage_secondary_4" -77.528809 11.014526 -43.908203 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_390" "airliner_fuselage_secondary_4" -77.424316 26.557983 -117.253418 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_391" "airliner_fuselage_secondary_4" -6.951172 -103.165161 -281.969482 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_392" "airliner_fuselage_secondary_4" -38.09082 -84.290344 -388.721436 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_393" "airliner_fuselage_secondary_4" 12.549316 -107.542603 210.054688 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_394" "airliner_fuselage_secondary_4" -60.705078 -61.377808 -6.415039 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_395" "airliner_fuselage_secondary_4" 7.240234 -41.322144 -742.185059 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_396" "airliner_fuselage_secondary_4" -13.140625 -63.269043 712.244629 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_397" "airliner_fuselage_secondary_4" 0.802734 -103.706543 259.017578 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_398" "airliner_fuselage_secondary_4" -21.431152 -93.589233 323.916016 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_399" "airliner_fuselage_secondary_4" -57.650879 -67.747864 426.662109 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_400" "airliner_fuselage_secondary_4" -24.746582 94.520142 506.136719 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_401" "airliner_fuselage_secondary_4" -67.37207 53.700562 210.059082 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_402" "airliner_fuselage_secondary_4" -77.202148 26.507324 -17.987305 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_403" "airliner_fuselage_secondary_4" -2.836914 103.606812 94.062012 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_404" "airliner_fuselage_secondary_4" -31.23877 95.533325 -488.631836 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_405" "airliner_fuselage_secondary_4" -77.136719 26.49939 434.356934 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_406" "airliner_fuselage_secondary_4" -60.551758 -55.415283 580.297852 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_407" "airliner_fuselage_secondary_4" -79.020996 4.7052 349.768555 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_408" "airliner_fuselage_secondary_4" 0.556641 104.667114 210.12207 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_409" "airliner_fuselage_secondary_4" -63.233398 61.856812 530.444336 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_410" "airliner_fuselage_secondary_4" 10.535156 -55.574585 769.09375 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_411" "airliner_fuselage_secondary_4" -78.589844 -24.893677 476.324219 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_412" "airliner_fuselage_secondary_4" -72.564941 -40.181885 284.827148 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_413" "airliner_fuselage_secondary_4" -32.934082 -90.013428 -255.463135 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_414" "airliner_fuselage_secondary_4" -73.334473 -36.352783 -72.030762 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_415" "airliner_fuselage_secondary_4" -2.784668 103.594604 -241.436523 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_416" "airliner_fuselage_secondary_4" -43.353516 83.189087 -59.564697 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_417" "airliner_fuselage_secondary_4" -35.209473 -87.895508 -317.359375 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_418" "airliner_fuselage_secondary_4" -27.144531 -80.075562 -469.185547 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_419" "airliner_fuselage_secondary_4" -58.370117 65.639282 -388.743652 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_420" "airliner_fuselage_secondary_4" -77.101563 -19.587158 -463.406738 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_421" "airliner_fuselage_secondary_4" -56.453125 -70.197754 42.134033 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_422" "airliner_fuselage_secondary_4" -71.847656 -46.881958 349.204102 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_423" "airliner_fuselage_secondary_4" -80.714844 0.219604 233.09082 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_424" "airliner_fuselage_secondary_4" -6.931152 -102.863525 508.914063 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_425" "airliner_fuselage_secondary_4" 8.566406 107.160034 -131.705078 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_426" "airliner_fuselage_secondary_4" -75.939453 29.903687 -458.394531 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_427" "airliner_fuselage_secondary_4" 0.756348 -103.671753 -164.490723 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_428" "airliner_fuselage_secondary_4" 1.650391 -105.001099 31.505859 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_429" "airliner_fuselage_secondary_4" -47.053711 50.586548 -669.214844 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_430" "airliner_fuselage_secondary_4" -21.088379 -25.510132 -734.568359 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_431" "airliner_fuselage_secondary_4" -6.918945 103.208862 -388.708496 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_432" "airliner_fuselage_secondary_4" -61.985352 -58.799133 154.317871 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_433" "airliner_fuselage_secondary_4" -56.661621 65.291626 -280.365234 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_434" "airliner_fuselage_secondary_4" -61.854492 -58.766113 513.473633 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_435" "airliner_fuselage_secondary_4" -73.324707 -34.977905 330.598633 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_436" "airliner_fuselage_secondary_4" -6.958496 -102.956665 219.400391 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_437" "airliner_fuselage_secondary_4" -2.778809 103.619507 -317.275879 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_438" "airliner_fuselage_secondary_4" -72.560547 -40.189697 197.740967 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_439" "airliner_fuselage_secondary_4" -58.902344 -65.294678 -100.400879 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_440" "airliner_fuselage_secondary_4" -73.318359 -36.463684 -201.312012 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_441" "airliner_fuselage_secondary_4" 2.245605 105.19812 154.404297 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_442" "airliner_fuselage_secondary_4" -37.23291 74.33313 -419.671387 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_443" "airliner_fuselage_secondary_4" -10.87793 -101.661743 280.619141 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_444" "airliner_fuselage_secondary_4" -21.5625 -95.272339 59.598633 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_445" "airliner_fuselage_secondary_4" -67.446289 53.701782 -43.316406 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_446" "airliner_fuselage_secondary_4" -61.245605 -55.433594 -423.523926 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_447" "airliner_fuselage_secondary_4" -43.355469 83.1875 73.105957 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_448" "airliner_fuselage_secondary_4" -77.351074 21.453247 258.07959 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_449" "airliner_fuselage_secondary_4" -2.874023 103.607422 -97.375488 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_450" "airliner_fuselage_secondary_4" -67.211914 53.635498 -248.220459 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_451" "airliner_fuselage_secondary_4" -41.085938 -84.499512 131.694824 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_452" "airliner_fuselage_secondary_4" -21.431641 -93.59082 365.939453 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_453" "airliner_fuselage_secondary_4" -21.327148 -93.808411 -268.332031 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_454" "airliner_fuselage_secondary_4" -33.143555 -89.662231 -154.772461 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_455" "airliner_fuselage_secondary_4" -56.505859 -70.175659 98.713379 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_456" "airliner_fuselage_secondary_4" 14.098633 -82.847839 704.820801 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_457" "airliner_fuselage_secondary_4" 8.168945 -107.117065 330.347656 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_458" "airliner_fuselage_secondary_4" -34.654297 -65.985291 654.536133 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_459" "airliner_fuselage_secondary_4" -56.713867 65.268188 484.595215 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_460" "airliner_fuselage_secondary_4" -79.253906 -5.06665 284.21582 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_461" "airliner_fuselage_secondary_4" 10.608398 -107.397034 -230.439697 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_462" "airliner_fuselage_secondary_4" -38.401855 84.780151 174.925781 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_463" "airliner_fuselage_secondary_4" -71.046387 46.040405 10.255371 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_464" "airliner_fuselage_secondary_4" -31.551758 -91.094116 -352.956543 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_465" "airliner_fuselage_secondary_4" -77.569824 13.738159 -169.322998 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_466" "airliner_fuselage_secondary_4" -44.665039 41.567017 -700.69458 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_467" "airliner_fuselage_secondary_4" -16.133301 -39.392456 -704.992188 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_468" "airliner_fuselage_secondary_4" -0.93457 94.571899 -671.90918 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_469" "airliner_fuselage_secondary_4" -56.523438 -70.181519 354.959961 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_470" "airliner_fuselage_secondary_4" -61.867188 -58.805054 468.009766 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_471" "airliner_fuselage_secondary_4" -80.608887 0.204712 459.691895 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_472" "airliner_fuselage_secondary_4" -77.25 26.522827 400.030762 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_473" "airliner_fuselage_secondary_4" -26.605957 -93.929077 265.000977 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_474" "airliner_fuselage_secondary_4" -68.285156 -51.66394 -15.269531 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_475" "airliner_fuselage_secondary_4" -56.510742 -70.311523 -181.388184 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_476" "airliner_fuselage_secondary_4" -80.680664 0.209106 -37.603027 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_477" "airliner_fuselage_secondary_4" -43.393555 83.189331 -66.199219 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_478" "airliner_fuselage_secondary_4" -43.235352 83.140747 -267.92334 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_479" "airliner_fuselage_secondary_4" -58.703613 -68.427124 -329.956299 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_480" "airliner_fuselage_secondary_4" 16.227051 -80.765015 -560.358887 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_481" "airliner_fuselage_secondary_4" -57.086914 11.679321 -654.976563 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_482" "airliner_fuselage_secondary_4" -42.701172 -49.139038 703.522461 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_483" "airliner_fuselage_secondary_4" 16.261719 107.913208 -355.713135 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_484" "airliner_fuselage_secondary_4" -26.620117 -91.882568 44.612793 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_485" "airliner_fuselage_secondary_4" -78.745605 5.739868 -476.160156 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_486" "airliner_fuselage_secondary_4" -63.323242 63.152832 -432.497559 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_487" "airliner_fuselage_secondary_4" -32.338379 86.710815 -333.071045 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_488" "airliner_fuselage_secondary_4" -33.03418 -89.749512 200.820313 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_489" "airliner_fuselage_secondary_4" -57.469727 68.63562 -8.893311 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_490" "airliner_fuselage_secondary_4" -70.92041 46.312866 -273.006348 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_491" "airliner_fuselage_secondary_4" -41.60498 85.147095 -310.56543 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_492" "airliner_fuselage_secondary_4" -78.210938 -24.398682 -434.061523 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_493" "airliner_fuselage_secondary_4" 33.359375 -77.230103 -570.331543 0 0 0 0 0 0 0 0 0
$definebone "baked_fuselage_debris_secondary_494" "airliner_fuselage_secondary_4" 69.949219 -86.011902 -459.509277 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "airliner_fuselage_secondary_4" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_373" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_374" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_375" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_376" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_377" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_378" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_379" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_380" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_381" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_382" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_383" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_384" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_385" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_386" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_387" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_388" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_389" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_390" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_391" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_392" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_393" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_394" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_395" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_396" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_397" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_398" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_399" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_400" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_401" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_402" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_403" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_404" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_405" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_406" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_407" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_408" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_409" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_410" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_411" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_412" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_413" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_414" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_415" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_416" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_417" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_418" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_419" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_420" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_421" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_422" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_423" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_424" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_425" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_426" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_427" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_428" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_429" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_430" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_431" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_432" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_433" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_434" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_435" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_436" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_437" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_438" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_439" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_440" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_441" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_442" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_443" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_444" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_445" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_446" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_447" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_448" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_449" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_450" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_451" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_452" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_453" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_454" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_455" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_456" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_457" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_458" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_459" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_460" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_461" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_462" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_463" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_464" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_465" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_466" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_467" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_468" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_469" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_470" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_471" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_472" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_473" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_474" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_475" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_476" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_477" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_478" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_479" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_480" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_481" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_482" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_483" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_484" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_485" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_486" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_487" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_488" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_489" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_490" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_491" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_492" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_493" position rotation
$bonesaveframe "baked_fuselage_debris_secondary_494" position rotation

$sectionframes 30 597

$sequence "idle" {
	"airliner_fuselage_secondary_4_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "idleOuttaMap" {
	"airliner_fuselage_secondary_4_anims\idleOuttaMap.smd"
	fadein 0.2
	fadeout 0.2
	node "idle"
	snap
	fps 30
}

$sequence "boom" {
	"airliner_fuselage_secondary_4_anims\boom.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
